package main

import(
 "context";"errors";"fmt";"log";"net";"net/http";"net/url";"os";"path/filepath";"strings";"time"
 "github.com/liuxb99/openworker/go-runtime/internal/api";"github.com/liuxb99/openworker/go-runtime/internal/buildinfo";"github.com/liuxb99/openworker/go-runtime/internal/cluster";owruntime "github.com/liuxb99/openworker/go-runtime/internal/runtime";"github.com/liuxb99/openworker/go-runtime/internal/store"
)
type nodeConfig struct{Listen string;Advertise string;DataDir string;Workers int;Capabilities string;Peers string}
func normalizeConfig(cfg nodeConfig)(nodeConfig,error){if cfg.Listen==""{cfg.Listen="127.0.0.1:8787"};if cfg.Workers<=0{cfg.Workers=4};if cfg.DataDir==""{if v:=os.Getenv("OPENWORKER_NODE_DATA");v!=""{cfg.DataDir=v}else{cfg.DataDir=filepath.Join(os.TempDir(),"openworker-node")}};if cfg.Capabilities==""{cfg.Capabilities=os.Getenv("OPENWORKER_NODE_CAPABILITIES")};if cfg.Peers==""{cfg.Peers=os.Getenv("OPENWORKER_CLUSTER_PEERS")};if cfg.Advertise==""{cfg.Advertise=os.Getenv("OPENWORKER_NODE_ADVERTISE")};if cfg.Advertise==""{cfg.Advertise=localEndpoint(cfg.Listen)};u,err:=url.Parse(cfg.Advertise);if err!=nil||u.Scheme==""||u.Host==""{return cfg,fmt.Errorf("invalid advertise endpoint: %s",cfg.Advertise)};cfg.Advertise=strings.TrimRight(cfg.Advertise,"/");if err:=os.MkdirAll(cfg.DataDir,0755);err!=nil{return cfg,err};return cfg,nil}
func splitPeers(v string)[]string{out:=[]string{};seen:=map[string]bool{};for _,x:=range strings.Split(v,","){if x=strings.TrimRight(strings.TrimSpace(x),"/");x!=""&&!seen[x]{seen[x]=true;out=append(out,x)}};return out}
func localEndpoint(listen string)string{host,port,err:=net.SplitHostPort(listen);if err!=nil{return "http://127.0.0.1:8787"};if host==""||host=="0.0.0.0"||host=="::"{host="127.0.0.1"};return "http://"+net.JoinHostPort(host,port)}
func runNode(ctx context.Context,cfg nodeConfig)error{cfg,err:=normalizeConfig(cfg);if err!=nil{return err};if cfg.Capabilities!=""{_=os.Setenv("OPENWORKER_NODE_CAPABILITIES",cfg.Capabilities)};machine,err:=os.Hostname();if err!=nil{return err};st,err:=store.Open(filepath.Join(cfg.DataDir,"openworker-node.sqlite3"));if err!=nil{return err};defer st.Close();nodeID:=strings.ToLower(machine);commit:=buildinfo.Snapshot()["commit"];_=st.RecordClusterEndpoint(store.ClusterEndpointReceipt{NodeID:nodeID,Machine:machine,Listen:cfg.Listen,Advertise:cfg.Advertise,Peers:cfg.Peers,BuildCommit:commit});rt:=owruntime.New(st,cfg.Workers,filepath.Join(cfg.DataDir,"logs"),machine);if err:=rt.Start();err!=nil{return err};defer rt.Stop();peers:=append([]string{localEndpoint(cfg.Listen)},splitPeers(cfg.Peers)...);cc:=cluster.NewController(peers);cc.SetProbeObserver(func(o cluster.ProbeObservation){v:=store.ClusterConnectivity{ObserverNodeID:nodeID,TargetEndpoint:o.Endpoint,TargetNodeID:o.Node.NodeID,TargetMachine:o.Node.Machine,OK:o.Err==nil,LatencyMS:o.Latency.Milliseconds(),ObservedAt:o.ObservedAt};if o.Err!=nil{v.Error=o.Err.Error()};_=st.RecordClusterConnectivity(v)});cc.Start(ctx);defer cc.Stop();srv:=&http.Server{Addr:cfg.Listen,Handler:api.New(st,rt,machine,cfg.Advertise,cc).Handler(),ReadHeaderTimeout:5*time.Second};errCh:=make(chan error,1);go func(){log.Printf("openworker-node machine=%s listen=%s advertise=%s workers=%d data=%s capabilities=%s peers=%s",machine,cfg.Listen,cfg.Advertise,cfg.Workers,cfg.DataDir,cfg.Capabilities,cfg.Peers);if e:=srv.ListenAndServe();e!=nil&&!errors.Is(e,http.ErrServerClosed){errCh<-e;return};errCh<-nil}();select{case<-ctx.Done():shutdownCtx,cancel:=context.WithTimeout(context.Background(),10*time.Second);defer cancel();if err:=srv.Shutdown(shutdownCtx);err!=nil{return fmt.Errorf("http shutdown: %w",err)};return nil;case err:=<-errCh:return err}}
