package runtime_test

import (
	"fmt"
	"os"
	"path/filepath"
	gort "runtime"
	"strings"
	"testing"
	"time"

	"github.com/liuxb99/openworker/go-runtime/internal/model"
	owruntime "github.com/liuxb99/openworker/go-runtime/internal/runtime"
	"github.com/liuxb99/openworker/go-runtime/internal/store"
)

func slowCommand() string { if gort.GOOS=="windows" { return `powershell -NoProfile -Command "Start-Sleep -Seconds 2"` }; return `sleep 2` }
func failingCommand() string { if gort.GOOS=="windows" { return `powershell -NoProfile -Command "[Console]::Error.WriteLine('boom-detail'); exit 7"` }; return `sh -c 'echo boom-detail 1>&2; exit 7'` }
func waitStatus(t *testing.T, st *store.Store, want map[model.Status]int, timeout time.Duration){deadline:=time.Now().Add(timeout);for time.Now().Before(deadline){jobs,err:=st.List(100);if err!=nil{t.Fatal(err)};counts:=map[model.Status]int{};for _,j:=range jobs{counts[j.Status]++};ok:=true;for s,n:=range want{if counts[s]!=n{ok=false;break}};if ok{return};time.Sleep(100*time.Millisecond)};jobs,_:=st.List(100);t.Fatalf("statuses not reached, jobs=%#v",jobs)}
func waitExecutionSummary(t *testing.T,st *store.Store,id string,timeout time.Duration)string{deadline:=time.Now().Add(timeout);for time.Now().Before(deadline){events,err:=st.Events(id,100);if err!=nil{t.Fatal(err)};for _,e:=range events{if e.EventType=="execution_summary"{return e.Detail}};time.Sleep(25*time.Millisecond)};t.Fatalf("execution_summary not durable for %s",id);return ""}
func TestFourWorkersRunAndFifthQueues(t *testing.T){root:=t.TempDir();st,err:=store.Open(filepath.Join(root,"node.sqlite3"));if err!=nil{t.Fatal(err)};defer st.Close();rt:=owruntime.New(st,4,filepath.Join(root,"logs"),"TESTHOST");if err:=rt.Start();err!=nil{t.Fatal(err)};defer rt.Stop();cwd:=t.TempDir();for i:=1;i<=5;i++{_,err:=st.Submit(model.SubmitRequest{JobID:fmt.Sprintf("OWJ-%d",i),DispatchID:fmt.Sprintf("OWD-%d",i),Machine:"TESTHOST",Command:slowCommand(),CWD:cwd,TimeoutSec:10},"TESTHOST");if err!=nil{t.Fatal(err)}};waitStatus(t,st,map[model.Status]int{model.StatusRunning:4,model.StatusQueued:1},5*time.Second);waitStatus(t,st,map[model.Status]int{model.StatusSucceeded:5},10*time.Second)}
func TestSharedResourceLockSerializesJobs(t *testing.T){root:=t.TempDir();st,err:=store.Open(filepath.Join(root,"node.sqlite3"));if err!=nil{t.Fatal(err)};defer st.Close();rt:=owruntime.New(st,2,filepath.Join(root,"logs"),"TESTHOST");if err:=rt.Start();err!=nil{t.Fatal(err)};defer rt.Stop();cwd:=t.TempDir();lock:=[]string{"workspace:"+cwd};for i:=1;i<=2;i++{_,err:=st.Submit(model.SubmitRequest{JobID:fmt.Sprintf("LOCK-%d",i),DispatchID:fmt.Sprintf("LOCK-D-%d",i),Machine:"TESTHOST",Command:slowCommand(),CWD:cwd,TimeoutSec:10,Locks:lock},"TESTHOST");if err!=nil{t.Fatal(err)}};waitStatus(t,st,map[model.Status]int{model.StatusRunning:1,model.StatusQueued:1},5*time.Second);waitStatus(t,st,map[model.Status]int{model.StatusSucceeded:2},10*time.Second)}
func TestCancelQueuedJob(t *testing.T){root:=t.TempDir();st,err:=store.Open(filepath.Join(root,"node.sqlite3"));if err!=nil{t.Fatal(err)};defer st.Close();rt:=owruntime.New(st,1,filepath.Join(root,"logs"),"TESTHOST");if err:=rt.Start();err!=nil{t.Fatal(err)};defer rt.Stop();cwd:=t.TempDir();_,_=st.Submit(model.SubmitRequest{JobID:"OWJ-A",DispatchID:"OWD-A",Machine:"TESTHOST",Command:slowCommand(),CWD:cwd,TimeoutSec:10},"TESTHOST");_,_=st.Submit(model.SubmitRequest{JobID:"OWJ-B",DispatchID:"OWD-B",Machine:"TESTHOST",Command:slowCommand(),CWD:cwd,TimeoutSec:10},"TESTHOST");waitStatus(t,st,map[model.Status]int{model.StatusRunning:1,model.StatusQueued:1},5*time.Second);if err:=rt.Cancel("OWJ-B");err!=nil{t.Fatal(err)};j,err:=st.Get("OWJ-B");if err!=nil{t.Fatal(err)};if j.Status!=model.StatusCancelled{t.Fatalf("expected cancelled, got %s",j.Status)};if err:=rt.Cancel("OWJ-A");err!=nil{t.Fatal(err)};waitStatus(t,st,map[model.Status]int{model.StatusCancelled:2},3*time.Second)}
func TestFailedJobPersistsExplainableExecutionSummary(t *testing.T){root:=t.TempDir();st,err:=store.Open(filepath.Join(root,"node.sqlite3"));if err!=nil{t.Fatal(err)};defer st.Close();rt:=owruntime.New(st,1,filepath.Join(root,"logs"),"TESTHOST");if err:=rt.Start();err!=nil{t.Fatal(err)};defer rt.Stop();cwd:=t.TempDir();_,err=st.Submit(model.SubmitRequest{JobID:"FAIL-1",DispatchID:"FAIL-D-1",Machine:"TESTHOST",Command:failingCommand(),CWD:cwd,WorkspaceRoot:cwd,TimeoutSec:10},"TESTHOST");if err!=nil{t.Fatal(err)};waitStatus(t,st,map[model.Status]int{model.StatusFailed:1},5*time.Second);detail:=waitExecutionSummary(t,st,"FAIL-1",2*time.Second);if !strings.Contains(detail,"\"succeeded\":false"){t.Fatalf("missing succeeded=false: %s",detail)};if !strings.Contains(detail,"boom-detail"){t.Fatalf("missing stderr tail: %s",detail)};if !strings.Contains(detail,"\"next_action\""){t.Fatalf("missing next_action: %s",detail)}}
func TestWindowsQuotedExecutableCommand(t *testing.T){if gort.GOOS!="windows"{t.Skip("windows quoting regression")};root:=t.TempDir();st,err:=store.Open(filepath.Join(root,"node.sqlite3"));if err!=nil{t.Fatal(err)};defer st.Close();rt:=owruntime.New(st,1,filepath.Join(root,"logs"),"TESTHOST");if err:=rt.Start();err!=nil{t.Fatal(err)};defer rt.Stop();cwd:=t.TempDir();cmd:=fmt.Sprintf("\"%s\" -test.run=TestNameThatDoesNotExist",os.Args[0]);_,err=st.Submit(model.SubmitRequest{JobID:"QUOTE-1",DispatchID:"QUOTE-D-1",Machine:"TESTHOST",Command:cmd,CWD:cwd,TimeoutSec:10},"TESTHOST");if err!=nil{t.Fatal(err)};waitStatus(t,st,map[model.Status]int{model.StatusSucceeded:1},10*time.Second)}
