package runtime

import(
 "bufio";"context";"encoding/json";"errors";"fmt";"os";"os/exec";"path/filepath";gort "runtime";"strconv";"strings";"sync";"time"
 "github.com/liuxb99/openworker/go-runtime/internal/locks";"github.com/liuxb99/openworker/go-runtime/internal/model";"github.com/liuxb99/openworker/go-runtime/internal/store";"github.com/liuxb99/openworker/go-runtime/internal/worktree"
)
type Manager struct{store *store.Store;maxWorkers int;logsDir,machine string;locks *locks.Manager;mu sync.Mutex;cancel map[string]context.CancelFunc;done map[string]chan struct{};stop chan struct{};wg sync.WaitGroup}
func New(st *store.Store,maxWorkers int,logsDir,machine string)*Manager{if maxWorkers<=0{maxWorkers=4};return &Manager{store:st,maxWorkers:maxWorkers,logsDir:logsDir,machine:machine,locks:locks.New(),cancel:map[string]context.CancelFunc{},done:map[string]chan struct{}{},stop:make(chan struct{})}}
func(m *Manager)recoverStartup()error{jobs,err:=m.store.ActiveJobs();if err!=nil{return err};for _,j:=range jobs{alive:=processAlive(j.PID);if alive{killProcessTree(j.PID)};detail:=fmt.Sprintf("startup recovery pid=%d alive=%t",j.PID,alive);if alive{detail+=" orphan process tree terminated before marking stale"};if err:=m.store.MarkStale(j.JobID,detail);err!=nil{return err}};return nil}
func(m *Manager)Start()error{if err:=os.MkdirAll(m.logsDir,0755);err!=nil{return err};if err:=m.recoverStartup();err!=nil{return err};for i:=0;i<m.maxWorkers;i++{m.wg.Add(1);go m.worker(i+1)};return nil}
func(m *Manager)Stop(){close(m.stop);m.mu.Lock();for _,c:=range m.cancel{c()};m.mu.Unlock();m.wg.Wait()}
func(m *Manager)worker(slot int){defer m.wg.Done();t:=time.NewTicker(300*time.Millisecond);defer t.Stop();for{select{case<-m.stop:return;case<-t.C:j,e:=m.store.ClaimNext();if e!=nil||j==nil{continue};if !m.locks.TryAcquire(j.JobID,j.Locks){_=m.store.Requeue(j.JobID,"resource lock busy");continue};m.run(slot,*j)}}}
func commandForShell(ctx context.Context,c string)*exec.Cmd{return platformCommandForShell(ctx,c)}
func statusSucceeded(status model.Status)bool{return status==model.StatusSucceeded}
func nextActionFor(status model.Status,detail string)string{if status==model.StatusSucceeded{return "continue to the next accepted workflow step"};if status==model.StatusTimedOut{return "inspect stderr/stdout and timeout requirements, then retry only after correcting the cause"};if status==model.StatusCancelled{return "confirm whether cancellation was intentional before retrying"};if strings.Contains(strings.ToLower(detail),"machine mismatch"){return "route the job to the requested COMPUTERNAME and retry"};if strings.Contains(strings.ToLower(detail),"worktree"){return "repair the worktree/repository state and retry"};if strings.Contains(strings.ToLower(detail),"start failed"){return "repair executable/path/environment prerequisites and retry"};return "inspect stderr_tail and the failing tool receipt, repair the root cause, then retry"}
func readTail(path string,n int)[]string{if path==""{return nil};v,e:=ReadLastLines(path,n);if e!=nil{return nil};return v}
func(m *Manager)finish(j model.Job,status model.Status,exit int,detail string){_=m.store.Finish(j.JobID,status,exit);m.store.RecordEvent(j.JobID,string(status),detail);cur,_:=m.store.Get(j.JobID);stderrTail:=readTail(cur.StderrPath,40);stdoutTail:=readTail(cur.StdoutPath,20);summary:=map[string]any{"schema":"openworker.execution-summary/v1","job_id":j.JobID,"dispatch_id":j.DispatchID,"machine":m.machine,"status":status,"succeeded":statusSucceeded(status),"attempted_action":j.Command,"cwd":j.CWD,"workspace_root":j.WorkspaceRoot,"exit_code":exit,"reason":detail,"stdout_path":cur.StdoutPath,"stderr_path":cur.StderrPath,"stdout_tail":stdoutTail,"stderr_tail":stderrTail,"started_at":cur.StartedAt,"finished_at":cur.FinishedAt,"next_action":nextActionFor(status,detail),"recorded_at":time.Now().UTC()};b,_:=json.Marshal(summary);m.store.RecordEvent(j.JobID,"execution_summary",string(b))}
func(m *Manager)run(slot int,j model.Job){defer m.locks.Release(j.JobID);m.store.RecordEvent(j.JobID,"attempt",fmt.Sprintf("machine=%s cwd=%s workspace=%s command=%s",m.machine,j.CWD,j.WorkspaceRoot,j.Command));if j.Machine!=""&&j.Machine!="any"&&!strings.EqualFold(j.Machine,m.machine){m.finish(j,model.StatusFailed,-1,"machine mismatch at execution");return};cwd:=j.CWD;if j.UseWorktree{p,e:=worktree.New(j.CWD).Ensure(slot,j.WorktreeRef);if e!=nil{m.finish(j,model.StatusFailed,-1,"worktree setup failed: "+e.Error());return};cwd=p};ctx,cancel:=context.WithTimeout(context.Background(),time.Duration(j.TimeoutSec)*time.Second);outp:=filepath.Join(m.logsDir,j.JobID+".stdout.log");errp:=filepath.Join(m.logsDir,j.JobID+".stderr.log");runDone:=make(chan struct{});m.mu.Lock();m.cancel[j.JobID]=cancel;m.done[j.JobID]=runDone;m.mu.Unlock();defer func(){cancel();if e:=waitForReleasedLogs(outp,errp);e!=nil{m.store.RecordEvent(j.JobID,"cleanup_warning",e.Error())};m.mu.Lock();delete(m.cancel,j.JobID);delete(m.done,j.JobID);m.mu.Unlock();close(runDone)}();out,e:=os.Create(outp);if e!=nil{m.finish(j,model.StatusFailed,-1,"stdout create failed: "+e.Error());return};defer out.Close();erf,e:=os.Create(errp);if e!=nil{m.finish(j,model.StatusFailed,-1,"stderr create failed: "+e.Error());return};defer erf.Close();cmd:=commandForShell(ctx,j.Command);cmd.Dir=cwd;cmd.Stdout=out;cmd.Stderr=erf;cmd.Env=os.Environ();for k,v:=range j.Env{cmd.Env=append(cmd.Env,k+"="+v)};cmd.Env=append(cmd.Env,"OPENWORKER_JOB_ID="+j.JobID,"OPENWORKER_AGENT_SLOT="+strconv.Itoa(slot),"OPENWORKER_MACHINE="+m.machine,"GITHUB_WORKSPACE="+cwd);if j.WorkspaceRoot!=""{cmd.Env=append(cmd.Env,"OPENWORKER_WORKSPACE="+j.WorkspaceRoot)};if e:=cmd.Start();e!=nil{m.finish(j,model.StatusFailed,-1,"process start failed: "+e.Error());return};_=m.store.MarkRunning(j.JobID,slot,cmd.Process.Pid,outp,errp);m.store.RecordEvent(j.JobID,"running",fmt.Sprintf("slot=%d pid=%d cwd=%s",slot,cmd.Process.Pid,cwd));done:=make(chan error,1);go func(){done<-cmd.Wait()}();hb:=time.NewTicker(2*time.Second);defer hb.Stop();for{select{case e:=<-done:exit:=0;status:=model.StatusSucceeded;detail:="process exited successfully";if e!=nil{status=model.StatusFailed;detail=e.Error();if ee:=new(exec.ExitError);errors.As(e,&ee){exit=ee.ExitCode()}else{exit=-1}};if ctx.Err()==context.DeadlineExceeded{status=model.StatusTimedOut;exit=-1;detail="timeout exceeded"};if ctx.Err()==context.Canceled{cur,_:=m.store.Get(j.JobID);if cur.Status==model.StatusCancelled{status=model.StatusCancelled;detail="cancelled by operator"}};m.finish(j,status,exit,detail);return;case<-hb.C:_=m.store.Heartbeat(j.JobID);case<-ctx.Done():killProcessTree(cmd.Process.Pid)}}}
func killProcessTree(pid int){if pid<=0{return};if gort.GOOS=="windows"{_=exec.Command("taskkill","/PID",strconv.Itoa(pid),"/T","/F").Run();return};if p,e:=os.FindProcess(pid);e==nil{_=p.Kill()}}
func(m *Manager)waitCleanup(id string,done chan struct{})error{if done==nil{return nil};select{case<-done:return nil;case<-time.After(7*time.Second):return fmt.Errorf("timeout waiting for deterministic worker cleanup: %s",id)}}
func(m *Manager)Cancel(id string)error{j,e:=m.store.Get(id);if e!=nil{return e};m.mu.Lock();c:=m.cancel[id];done:=m.done[id];m.mu.Unlock();if j.Status==model.StatusSucceeded||j.Status==model.StatusFailed||j.Status==model.StatusTimedOut||j.Status==model.StatusCancelled{return m.waitCleanup(id,done)};_=m.store.MarkCancelled(id);m.store.RecordEvent(id,"cancel_requested","operator cancel");if c!=nil{c();if j.PID>0{killProcessTree(j.PID)}};if e:=m.waitCleanup(id,done);e!=nil{return e};m.locks.Release(id);return nil}
func(m *Manager)Retry(id string)error{return m.store.Retry(id,"explicit operator retry")}
func(m *Manager)DrainQueued()([]string,error){ids,e:=m.store.DrainQueued();if e==nil{for _,id:=range ids{m.store.RecordEvent(id,"drained","queued drain")}};return ids,e}
func(m *Manager)DrainAll()([]string,error){jobs,e:=m.store.List(1000);if e!=nil{return nil,e};ids:=[]string{};for _,j:=range jobs{switch j.Status{case model.StatusQueued,model.StatusStarting,model.StatusRunning:if e:=m.Cancel(j.JobID);e!=nil{return ids,e};m.store.RecordEvent(j.JobID,"drained","drain all");ids=append(ids,j.JobID)}};return ids,e}
func(m *Manager)NodeStatus()map[string]any{jobs,_:=m.store.List(1000);busy,q:=0,0;for _,j:=range jobs{if j.Status==model.StatusRunning||j.Status==model.StatusStarting{busy++};if j.Status==model.StatusQueued{q++}};return map[string]any{"machine":m.machine,"online":true,"max_workers":m.maxWorkers,"busy_workers":busy,"free_workers":max(0,m.maxWorkers-busy),"queued_jobs":q,"resource_locks":m.locks.Snapshot(),"time":time.Now().UTC()}}
func ReadLastLines(path string,n int)([]string,error){f,e:=os.Open(path);if e!=nil{return nil,e};defer f.Close();s:=bufio.NewScanner(f);ls:=[]string{};for s.Scan(){ls=append(ls,s.Text());if len(ls)>n{ls=ls[1:]}};return ls,s.Err()}
func ValidateCWD(p string)error{if p==""{return fmt.Errorf("cwd required")};st,e:=os.Stat(p);if e!=nil{return e};if !st.IsDir(){return fmt.Errorf("cwd is not a directory: %s",p)};return nil}
