package model

import "time"

type Status string
const(StatusAccepted Status="accepted";StatusQueued Status="queued_local";StatusStarting Status="starting";StatusRunning Status="running";StatusSucceeded Status="succeeded";StatusFailed Status="failed";StatusTimedOut Status="timed_out";StatusCancelled Status="cancelled";StatusStale Status="stale")
type Job struct{JobID string `json:"job_id"`;DispatchID string `json:"dispatch_id"`;Machine string `json:"machine"`;Status Status `json:"status"`;Priority int `json:"priority"`;Command string `json:"command"`;CWD string `json:"cwd"`;WorkspaceRoot string `json:"workspace_root,omitempty"`;Env map[string]string `json:"env,omitempty"`;TimeoutSec int `json:"timeout_sec"`;Locks []string `json:"locks,omitempty"`;UseWorktree bool `json:"use_worktree,omitempty"`;WorktreeRef string `json:"worktree_ref,omitempty"`;AgentSlot int `json:"agent_slot,omitempty"`;PID int `json:"pid,omitempty"`;ExitCode *int `json:"exit_code,omitempty"`;StdoutPath string `json:"stdout_path,omitempty"`;StderrPath string `json:"stderr_path,omitempty"`;CreatedAt time.Time `json:"created_at"`;AcceptedAt time.Time `json:"accepted_at"`;StartedAt *time.Time `json:"started_at,omitempty"`;FinishedAt *time.Time `json:"finished_at,omitempty"`;HeartbeatAt *time.Time `json:"heartbeat_at,omitempty"`}
type SubmitRequest struct{JobID string `json:"job_id"`;DispatchID string `json:"dispatch_id"`;Machine string `json:"machine"`;Priority int `json:"priority"`;Command string `json:"command"`;CWD string `json:"cwd"`;WorkspaceRoot string `json:"workspace_root,omitempty"`;Env map[string]string `json:"env,omitempty"`;TimeoutSec int `json:"timeout_sec"`;Locks []string `json:"locks,omitempty"`;UseWorktree bool `json:"use_worktree,omitempty"`;WorktreeRef string `json:"worktree_ref,omitempty"`}
type SubmitAck struct{JobID string `json:"job_id"`;DispatchID string `json:"dispatch_id"`;Machine string `json:"machine"`;Accepted bool `json:"accepted"`;AcceptedAt time.Time `json:"accepted_at"`;QueuePosition int `json:"queue_position"`;Duplicate bool `json:"duplicate"`}
