package store

import "time"

type ClusterEndpointReceipt struct{NodeID string `json:"node_id"`;Machine string `json:"machine"`;Listen string `json:"listen"`;Advertise string `json:"advertise"`;Peers string `json:"peers"`;BuildCommit string `json:"build_commit,omitempty"`;RecordedAt time.Time `json:"recorded_at"`}
type ClusterConnectivity struct{ID int64 `json:"id"`;ObserverNodeID string `json:"observer_node_id"`;TargetEndpoint string `json:"target_endpoint"`;TargetNodeID string `json:"target_node_id,omitempty"`;TargetMachine string `json:"target_machine,omitempty"`;OK bool `json:"ok"`;LatencyMS int64 `json:"latency_ms"`;Error string `json:"error,omitempty"`;ObservedAt time.Time `json:"observed_at"`}
func(s *Store)ensureConnectivity()error{_,err:=s.db.Exec(`CREATE TABLE IF NOT EXISTS cluster_endpoint_receipts(node_id TEXT PRIMARY KEY,machine TEXT NOT NULL,listen TEXT NOT NULL,advertise TEXT NOT NULL,peers TEXT NOT NULL DEFAULT '',build_commit TEXT NOT NULL DEFAULT '',recorded_at TEXT NOT NULL);CREATE TABLE IF NOT EXISTS cluster_connectivity_history(id INTEGER PRIMARY KEY AUTOINCREMENT,observer_node_id TEXT NOT NULL,target_endpoint TEXT NOT NULL,target_node_id TEXT NOT NULL DEFAULT '',target_machine TEXT NOT NULL DEFAULT '',ok INTEGER NOT NULL,latency_ms INTEGER NOT NULL DEFAULT 0,error TEXT NOT NULL DEFAULT '',observed_at TEXT NOT NULL);CREATE INDEX IF NOT EXISTS idx_cluster_connectivity_time ON cluster_connectivity_history(observed_at DESC);`);return err}
func(s *Store)RecordClusterEndpoint(r ClusterEndpointReceipt)error{if err:=s.ensureConnectivity();err!=nil{return err};if r.RecordedAt.IsZero(){r.RecordedAt=time.Now().UTC()};_,err:=s.db.Exec(`INSERT INTO cluster_endpoint_receipts(node_id,machine,listen,advertise,peers,build_commit,recorded_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(node_id) DO UPDATE SET machine=excluded.machine,listen=excluded.listen,advertise=excluded.advertise,peers=excluded.peers,build_commit=excluded.build_commit,recorded_at=excluded.recorded_at`,r.NodeID,r.Machine,r.Listen,r.Advertise,r.Peers,r.BuildCommit,nowText(r.RecordedAt));return err}
func(s *Store)ClusterEndpoints()([]ClusterEndpointReceipt,error){if err:=s.ensureConnectivity();err!=nil{return nil,err};rows,err:=s.db.Query(`SELECT node_id,machine,listen,advertise,peers,build_commit,recorded_at FROM cluster_endpoint_receipts ORDER BY node_id`);if err!=nil{return nil,err};defer rows.Close();out:=[]ClusterEndpointReceipt{};for rows.Next(){var r ClusterEndpointReceipt;var ts string;if err:=rows.Scan(&r.NodeID,&r.Machine,&r.Listen,&r.Advertise,&r.Peers,&r.BuildCommit,&ts);err!=nil{return nil,err};r.RecordedAt,_=time.Parse(time.RFC3339Nano,ts);out=append(out,r)};return out,rows.Err()}
func(s *Store)RecordClusterConnectivity(v ClusterConnectivity)error{if err:=s.ensureConnectivity();err!=nil{return err};if v.ObservedAt.IsZero(){v.ObservedAt=time.Now().UTC()};ok:=0;if v.OK{ok=1};_,err:=s.db.Exec(`INSERT INTO cluster_connectivity_history(observer_node_id,target_endpoint,target_node_id,target_machine,ok,latency_ms,error,observed_at) VALUES(?,?,?,?,?,?,?,?)`,v.ObserverNodeID,v.TargetEndpoint,v.TargetNodeID,v.TargetMachine,ok,v.LatencyMS,v.Error,nowText(v.ObservedAt));return err}
func(s *Store)ClusterConnectivityHistory(limit int)([]ClusterConnectivity,error){if err:=s.ensureConnectivity();err!=nil{return nil,err};if limit<=0||limit>2000{limit=200};rows,err:=s.db.Query(`SELECT id,observer_node_id,target_endpoint,target_node_id,target_machine,ok,latency_ms,error,observed_at FROM cluster_connectivity_history ORDER BY id DESC LIMIT ?`,limit);if err!=nil{return nil,err};defer rows.Close();out:=[]ClusterConnectivity{};for rows.Next(){var v ClusterConnectivity;var ok int;var ts string;if err:=rows.Scan(&v.ID,&v.ObserverNodeID,&v.TargetEndpoint,&v.TargetNodeID,&v.TargetMachine,&ok,&v.LatencyMS,&v.Error,&ts);err!=nil{return nil,err};v.OK=ok!=0;v.ObservedAt,_=time.Parse(time.RFC3339Nano,ts);out=append(out,v)};return out,rows.Err()}
