package store

import(
 "database/sql"
 "encoding/json"
 "time"
)

type ClusterDispatch struct{JobID string `json:"job_id"`;DispatchID string `json:"dispatch_id"`;RequestedMachine string `json:"requested_machine"`;SelectedNodeID string `json:"selected_node_id"`;SelectedMachine string `json:"selected_machine"`;Endpoint string `json:"endpoint"`;RequiredCapabilities []string `json:"required_capabilities"`;AcceptedAt time.Time `json:"accepted_at"`;CreatedAt time.Time `json:"created_at"`}
type ClusterControlEvent struct{ID int64 `json:"id"`;JobID string `json:"job_id,omitempty"`;Action string `json:"action"`;Target string `json:"target"`;Detail string `json:"detail"`;CreatedAt time.Time `json:"created_at"`}
func(s *Store)ensureClusterLedger()error{_,err:=s.db.Exec(`CREATE TABLE IF NOT EXISTS cluster_dispatches(job_id TEXT PRIMARY KEY,dispatch_id TEXT NOT NULL,requested_machine TEXT NOT NULL,selected_node_id TEXT NOT NULL,selected_machine TEXT NOT NULL,endpoint TEXT NOT NULL,required_capabilities_json TEXT NOT NULL DEFAULT '[]',accepted_at TEXT NOT NULL,created_at TEXT NOT NULL);CREATE UNIQUE INDEX IF NOT EXISTS idx_cluster_dispatch_id ON cluster_dispatches(dispatch_id);CREATE TABLE IF NOT EXISTS cluster_control_events(id INTEGER PRIMARY KEY AUTOINCREMENT,job_id TEXT NOT NULL DEFAULT '',action TEXT NOT NULL,target TEXT NOT NULL DEFAULT '',detail TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL);`);return err}
func(s *Store)RecordClusterDispatch(d ClusterDispatch)error{if err:=s.ensureClusterLedger();err!=nil{return err};caps,_:=json.Marshal(d.RequiredCapabilities);now:=time.Now().UTC();if d.CreatedAt.IsZero(){d.CreatedAt=now};_,err:=s.db.Exec(`INSERT OR IGNORE INTO cluster_dispatches(job_id,dispatch_id,requested_machine,selected_node_id,selected_machine,endpoint,required_capabilities_json,accepted_at,created_at) VALUES(?,?,?,?,?,?,?,?,?)`,d.JobID,d.DispatchID,d.RequestedMachine,d.SelectedNodeID,d.SelectedMachine,d.Endpoint,string(caps),nowText(d.AcceptedAt),nowText(d.CreatedAt));return err}
func(s *Store)ClusterDispatch(jobID string)(ClusterDispatch,error){if err:=s.ensureClusterLedger();err!=nil{return ClusterDispatch{},err};var d ClusterDispatch;var caps,accepted,created string;err:=s.db.QueryRow(`SELECT job_id,dispatch_id,requested_machine,selected_node_id,selected_machine,endpoint,required_capabilities_json,accepted_at,created_at FROM cluster_dispatches WHERE job_id=?`,jobID).Scan(&d.JobID,&d.DispatchID,&d.RequestedMachine,&d.SelectedNodeID,&d.SelectedMachine,&d.Endpoint,&caps,&accepted,&created);if err!=nil{return d,err};_=json.Unmarshal([]byte(caps),&d.RequiredCapabilities);d.AcceptedAt,_=time.Parse(time.RFC3339Nano,accepted);d.CreatedAt,_=time.Parse(time.RFC3339Nano,created);return d,nil}
func(s *Store)ClusterDispatches(limit int)([]ClusterDispatch,error){if err:=s.ensureClusterLedger();err!=nil{return nil,err};if limit<=0||limit>1000{limit=100};rows,err:=s.db.Query(`SELECT job_id,dispatch_id,requested_machine,selected_node_id,selected_machine,endpoint,required_capabilities_json,accepted_at,created_at FROM cluster_dispatches ORDER BY created_at DESC LIMIT ?`,limit);if err!=nil{return nil,err};defer rows.Close();out:=[]ClusterDispatch{};for rows.Next(){var d ClusterDispatch;var caps,accepted,created string;if err:=rows.Scan(&d.JobID,&d.DispatchID,&d.RequestedMachine,&d.SelectedNodeID,&d.SelectedMachine,&d.Endpoint,&caps,&accepted,&created);err!=nil{return nil,err};_=json.Unmarshal([]byte(caps),&d.RequiredCapabilities);d.AcceptedAt,_=time.Parse(time.RFC3339Nano,accepted);d.CreatedAt,_=time.Parse(time.RFC3339Nano,created);out=append(out,d)};return out,rows.Err()}
func(s *Store)RecordClusterControl(jobID,action,target,detail string)error{if err:=s.ensureClusterLedger();err!=nil{return err};_,err:=s.db.Exec(`INSERT INTO cluster_control_events(job_id,action,target,detail,created_at) VALUES(?,?,?,?,?)`,jobID,action,target,detail,nowText(time.Now().UTC()));return err}
func(s *Store)ClusterControlEvents(jobID string,limit int)([]ClusterControlEvent,error){if err:=s.ensureClusterLedger();err!=nil{return nil,err};if limit<=0||limit>1000{limit=100};var rows *sql.Rows;var err error;if jobID==""{rows,err=s.db.Query(`SELECT id,job_id,action,target,detail,created_at FROM cluster_control_events ORDER BY id DESC LIMIT ?`,limit)}else{rows,err=s.db.Query(`SELECT id,job_id,action,target,detail,created_at FROM cluster_control_events WHERE job_id=? ORDER BY id DESC LIMIT ?`,jobID,limit)};if err!=nil{return nil,err};defer rows.Close();out:=[]ClusterControlEvent{};for rows.Next(){var e ClusterControlEvent;var created string;if err:=rows.Scan(&e.ID,&e.JobID,&e.Action,&e.Target,&e.Detail,&created);err!=nil{return nil,err};e.CreatedAt,_=time.Parse(time.RFC3339Nano,created);out=append(out,e)};return out,rows.Err()}
