package store

import("database/sql";"encoding/json";"errors";"fmt";"strings";"time";_ "modernc.org/sqlite";"github.com/liuxb99/openworker/go-runtime/internal/model")
type Store struct{db *sql.DB}
func Open(path string)(*Store,error){db,err:=sql.Open("sqlite",path);if err!=nil{return nil,err};db.SetMaxOpenConns(1);s:=&Store{db:db};if err:=s.migrate();err!=nil{_=db.Close();return nil,err};return s,nil}
func(s *Store)Close()error{return s.db.Close()}
func(s *Store)migrate()error{_,err:=s.db.Exec(`PRAGMA journal_mode=WAL; PRAGMA busy_timeout=5000;
CREATE TABLE IF NOT EXISTS jobs (job_id TEXT PRIMARY KEY, dispatch_id TEXT NOT NULL UNIQUE, machine TEXT NOT NULL,status TEXT NOT NULL, priority INTEGER NOT NULL DEFAULT 0, command TEXT NOT NULL,cwd TEXT NOT NULL, workspace_root TEXT NOT NULL DEFAULT '', env_json TEXT NOT NULL DEFAULT '{}',timeout_sec INTEGER NOT NULL DEFAULT 3600, locks_json TEXT NOT NULL DEFAULT '[]',use_worktree INTEGER NOT NULL DEFAULT 0, worktree_ref TEXT NOT NULL DEFAULT '',agent_slot INTEGER NOT NULL DEFAULT 0,pid INTEGER NOT NULL DEFAULT 0, exit_code INTEGER, stdout_path TEXT NOT NULL DEFAULT '',stderr_path TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL, accepted_at TEXT NOT NULL,started_at TEXT, finished_at TEXT, heartbeat_at TEXT);
CREATE INDEX IF NOT EXISTS idx_jobs_status_priority ON jobs(status, priority DESC, created_at ASC);
CREATE TABLE IF NOT EXISTS job_events (id INTEGER PRIMARY KEY AUTOINCREMENT, job_id TEXT NOT NULL, event_type TEXT NOT NULL,detail TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL);`);if err!=nil{return err};for _,q:=range []string{`ALTER TABLE jobs ADD COLUMN locks_json TEXT NOT NULL DEFAULT '[]'`,`ALTER TABLE jobs ADD COLUMN use_worktree INTEGER NOT NULL DEFAULT 0`,`ALTER TABLE jobs ADD COLUMN worktree_ref TEXT NOT NULL DEFAULT ''`,`ALTER TABLE jobs ADD COLUMN agent_slot INTEGER NOT NULL DEFAULT 0`}{if _,e:=s.db.Exec(q);e!=nil&&!strings.Contains(strings.ToLower(e.Error()),"duplicate column"){return e}};return nil}
func nowText(t time.Time)string{return t.UTC().Format(time.RFC3339Nano)}
func parseTime(v sql.NullString)*time.Time{if !v.Valid||v.String==""{return nil};t,e:=time.Parse(time.RFC3339Nano,v.String);if e!=nil{return nil};return &t}
func(s *Store)event(jobID,eventType,detail string){_,_=s.db.Exec(`INSERT INTO job_events(job_id,event_type,detail,created_at) VALUES(?,?,?,?)`,jobID,eventType,detail,nowText(time.Now().UTC()))}
func(s *Store)RecordEvent(jobID,eventType,detail string){s.event(jobID,eventType,detail)}
func(s *Store)Submit(req model.SubmitRequest,actualMachine string)(model.SubmitAck,error){if req.JobID==""||req.DispatchID==""||req.Command==""||req.CWD==""{return model.SubmitAck{},errors.New("job_id, dispatch_id, command and cwd are required")};if req.TimeoutSec<=0{req.TimeoutSec=3600};if req.Machine!=""&&req.Machine!="any"&&!strings.EqualFold(req.Machine,actualMachine){return model.SubmitAck{},fmt.Errorf("machine mismatch: requested=%s actual=%s",req.Machine,actualMachine)};if req.Machine==""{req.Machine=actualMachine};envJSON,_:=json.Marshal(req.Env);locksJSON,_:=json.Marshal(req.Locks);now:=time.Now().UTC();wt:=0;if req.UseWorktree{wt=1};tx,err:=s.db.Begin();if err!=nil{return model.SubmitAck{},err};defer tx.Rollback();res,err:=tx.Exec(`INSERT OR IGNORE INTO jobs(job_id,dispatch_id,machine,status,priority,command,cwd,workspace_root,env_json,timeout_sec,locks_json,use_worktree,worktree_ref,agent_slot,created_at,accepted_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,req.JobID,req.DispatchID,actualMachine,string(model.StatusQueued),req.Priority,req.Command,req.CWD,req.WorkspaceRoot,string(envJSON),req.TimeoutSec,string(locksJSON),wt,req.WorktreeRef,0,nowText(now),nowText(now));if err!=nil{return model.SubmitAck{},err};rows,_:=res.RowsAffected();if rows==0{var ej,ed,m,a string;if err:=tx.QueryRow(`SELECT job_id,dispatch_id,machine,accepted_at FROM jobs WHERE job_id=? OR dispatch_id=?`,req.JobID,req.DispatchID).Scan(&ej,&ed,&m,&a);err!=nil{return model.SubmitAck{},err};if ej!=req.JobID||ed!=req.DispatchID{return model.SubmitAck{},fmt.Errorf("idempotency conflict: job_id or dispatch_id already belongs to another job")};t,_:=time.Parse(time.RFC3339Nano,a);var pos int;_=tx.QueryRow(`SELECT COUNT(*) FROM jobs WHERE status=?`,string(model.StatusQueued)).Scan(&pos);if err:=tx.Commit();err!=nil{return model.SubmitAck{},err};return model.SubmitAck{JobID:ej,DispatchID:ed,Machine:m,Accepted:true,AcceptedAt:t,QueuePosition:pos,Duplicate:true},nil};_,_=tx.Exec(`INSERT INTO job_events(job_id,event_type,detail,created_at) VALUES(?,?,?,?)`,req.JobID,"accepted","durable local accept",nowText(now));var pos int;_=tx.QueryRow(`SELECT COUNT(*) FROM jobs WHERE status=?`,string(model.StatusQueued)).Scan(&pos);if err:=tx.Commit();err!=nil{return model.SubmitAck{},err};return model.SubmitAck{JobID:req.JobID,DispatchID:req.DispatchID,Machine:actualMachine,Accepted:true,AcceptedAt:now,QueuePosition:pos},nil}
func scanJob(scanner interface{Scan(...any)error})(model.Job,error){var j model.Job;var status,envJSON,locksJSON,created,accepted string;var started,finished,heartbeat sql.NullString;var exitCode sql.NullInt64;var wt int;err:=scanner.Scan(&j.JobID,&j.DispatchID,&j.Machine,&status,&j.Priority,&j.Command,&j.CWD,&j.WorkspaceRoot,&envJSON,&j.TimeoutSec,&locksJSON,&wt,&j.WorktreeRef,&j.AgentSlot,&j.PID,&exitCode,&j.StdoutPath,&j.StderrPath,&created,&accepted,&started,&finished,&heartbeat);if err!=nil{return j,err};j.Status=model.Status(status);_=json.Unmarshal([]byte(envJSON),&j.Env);_=json.Unmarshal([]byte(locksJSON),&j.Locks);j.UseWorktree=wt!=0;j.CreatedAt,_=time.Parse(time.RFC3339Nano,created);j.AcceptedAt,_=time.Parse(time.RFC3339Nano,accepted);j.StartedAt=parseTime(started);j.FinishedAt=parseTime(finished);j.HeartbeatAt=parseTime(heartbeat);if exitCode.Valid{v:=int(exitCode.Int64);j.ExitCode=&v};return j,nil}
const selectCols=`job_id,dispatch_id,machine,status,priority,command,cwd,workspace_root,env_json,timeout_sec,locks_json,use_worktree,worktree_ref,agent_slot,pid,exit_code,stdout_path,stderr_path,created_at,accepted_at,started_at,finished_at,heartbeat_at`
func(s *Store)Get(jobID string)(model.Job,error){return scanJob(s.db.QueryRow(`SELECT `+selectCols+` FROM jobs WHERE job_id=?`,jobID))}
func(s *Store)List(limit int)([]model.Job,error){if limit<=0||limit>1000{limit=100};rows,err:=s.db.Query(`SELECT `+selectCols+` FROM jobs ORDER BY created_at DESC LIMIT ?`,limit);if err!=nil{return nil,err};defer rows.Close();out:=[]model.Job{};for rows.Next(){j,e:=scanJob(rows);if e!=nil{return nil,e};out=append(out,j)};return out,rows.Err()}
func(s *Store)ActiveJobs()([]model.Job,error){rows,err:=s.db.Query(`SELECT `+selectCols+` FROM jobs WHERE status IN (?,?) ORDER BY created_at ASC`,string(model.StatusStarting),string(model.StatusRunning));if err!=nil{return nil,err};defer rows.Close();out:=[]model.Job{};for rows.Next(){j,e:=scanJob(rows);if e!=nil{return nil,e};out=append(out,j)};return out,rows.Err()}
func(s *Store)ClaimNext()(*model.Job,error){tx,err:=s.db.Begin();if err!=nil{return nil,err};defer tx.Rollback();j,err:=scanJob(tx.QueryRow(`SELECT `+selectCols+` FROM jobs WHERE status=? ORDER BY priority DESC,created_at ASC LIMIT 1`,string(model.StatusQueued)));if errors.Is(err,sql.ErrNoRows){return nil,nil};if err!=nil{return nil,err};now:=time.Now().UTC();res,err:=tx.Exec(`UPDATE jobs SET status=?,started_at=?,heartbeat_at=?,agent_slot=0 WHERE job_id=? AND status=?`,string(model.StatusStarting),nowText(now),nowText(now),j.JobID,string(model.StatusQueued));if err!=nil{return nil,err};n,_:=res.RowsAffected();if n!=1{return nil,nil};_,_=tx.Exec(`INSERT INTO job_events(job_id,event_type,detail,created_at) VALUES(?,?,?,?)`,j.JobID,"claimed","worker slot claimed",nowText(now));if err:=tx.Commit();err!=nil{return nil,err};j.Status=model.StatusStarting;j.StartedAt=&now;j.HeartbeatAt=&now;return &j,nil}
func(s *Store)Requeue(jobID,reason string)error{_,err:=s.db.Exec(`UPDATE jobs SET status=?,started_at=NULL,heartbeat_at=NULL,agent_slot=0 WHERE job_id=? AND status=?`,string(model.StatusQueued),jobID,string(model.StatusStarting));if err==nil{s.event(jobID,"requeued",reason)};return err}
func(s *Store)Retry(jobID,reason string)error{j,err:=s.Get(jobID);if err!=nil{return err};switch j.Status{case model.StatusFailed,model.StatusTimedOut,model.StatusCancelled,model.StatusStale:default:return fmt.Errorf("job %s status %s is not retryable",jobID,j.Status)};res,err:=s.db.Exec(`UPDATE jobs SET status=?,pid=0,agent_slot=0,exit_code=NULL,started_at=NULL,finished_at=NULL,heartbeat_at=NULL WHERE job_id=? AND status=?`,string(model.StatusQueued),jobID,string(j.Status));if err!=nil{return err};n,_:=res.RowsAffected();if n!=1{return fmt.Errorf("job %s changed while retrying",jobID)};s.event(jobID,"retried",reason);return nil}
func(s *Store)MarkRunning(jobID string,slot,pid int,stdoutPath,stderrPath string)error{now:=time.Now().UTC();_,err:=s.db.Exec(`UPDATE jobs SET status=?,agent_slot=?,pid=?,stdout_path=?,stderr_path=?,heartbeat_at=? WHERE job_id=?`,string(model.StatusRunning),slot,pid,stdoutPath,stderrPath,nowText(now),jobID);return err}
func(s *Store)Heartbeat(jobID string)error{_,err:=s.db.Exec(`UPDATE jobs SET heartbeat_at=? WHERE job_id=? AND status=?`,nowText(time.Now().UTC()),jobID,string(model.StatusRunning));return err}
func(s *Store)Finish(jobID string,status model.Status,exitCode int)error{now:=time.Now().UTC();_,err:=s.db.Exec(`UPDATE jobs SET status=?,exit_code=?,finished_at=?,heartbeat_at=? WHERE job_id=?`,string(status),exitCode,nowText(now),nowText(now),jobID);return err}
func(s *Store)MarkStale(jobID,detail string)error{now:=time.Now().UTC();res,err:=s.db.Exec(`UPDATE jobs SET status=?,finished_at=?,heartbeat_at=? WHERE job_id=? AND status IN (?,?)`,string(model.StatusStale),nowText(now),nowText(now),jobID,string(model.StatusStarting),string(model.StatusRunning));if err!=nil{return err};n,_:=res.RowsAffected();if n==1{s.event(jobID,"stale",detail)};return nil}
func(s *Store)MarkCancelled(jobID string)error{now:=time.Now().UTC();_,err:=s.db.Exec(`UPDATE jobs SET status=?,finished_at=? WHERE job_id=? AND status IN (?,?,?)`,string(model.StatusCancelled),nowText(now),jobID,string(model.StatusQueued),string(model.StatusStarting),string(model.StatusRunning));return err}
func(s *Store)DrainQueued()([]string,error){rows,err:=s.db.Query(`SELECT job_id FROM jobs WHERE status=?`,string(model.StatusQueued));if err!=nil{return nil,err};defer rows.Close();ids:=[]string{};for rows.Next(){var id string;if err:=rows.Scan(&id);err!=nil{return nil,err};ids=append(ids,id)};now:=nowText(time.Now().UTC());_,err=s.db.Exec(`UPDATE jobs SET status=?,finished_at=? WHERE status=?`,string(model.StatusCancelled),now,string(model.StatusQueued));return ids,err}
func(s *Store)RecoverStale()(int,error){jobs,err:=s.ActiveJobs();if err!=nil{return 0,err};for _,j:=range jobs{if err:=s.MarkStale(j.JobID,"legacy startup recovery");err!=nil{return 0,err}};return len(jobs),nil}
