package cluster

import(
 "bytes";"encoding/json";"errors";"fmt";"io";"net/http";"net/url";"strconv";"strings";"time"
 "github.com/liuxb99/openworker/go-runtime/internal/model"
)
type ClusterJob struct{NodeID string `json:"node_id"`;Endpoint string `json:"endpoint"`;Job model.Job `json:"job"`}
type Agent struct{NodeID string `json:"node_id"`;Machine string `json:"machine"`;Slot int `json:"slot"`;Busy bool `json:"busy"`;JobID string `json:"job_id,omitempty"`;Status model.Status `json:"status,omitempty"`}
type SubmitRequest struct{Job model.SubmitRequest `json:"job"`;RequiredCapabilities []string `json:"required_capabilities,omitempty"`}
type SubmitResult struct{Selected Node `json:"selected"`;Ack model.SubmitAck `json:"ack"`}
type ControlResult struct{NodeID string `json:"node_id"`;Machine string `json:"machine"`;Endpoint string `json:"endpoint"`;Action string `json:"action"`;Response any `json:"response"`}
func(c *Controller)Jobs(limit int)([]ClusterJob,error){if limit<=0||limit>1000{limit=100};out:=[]ClusterJob{};var first error;for _,n:=range c.registry.Nodes(){if !n.Online{continue};resp,err:=c.client.Get(strings.TrimRight(n.Endpoint,"/")+"/v1/jobs?limit="+strconv.Itoa(limit));if err!=nil{if first==nil{first=err};continue};var body struct{Jobs []model.Job `json:"jobs"`};if resp.StatusCode/100==2{err=json.NewDecoder(resp.Body).Decode(&body)}else{err=errors.New(resp.Status)};resp.Body.Close();if err!=nil{if first==nil{first=err};continue};for _,j:=range body.Jobs{out=append(out,ClusterJob{NodeID:n.NodeID,Endpoint:n.Endpoint,Job:j})}};if len(out)==0&&first!=nil{return out,first};return out,nil}
func(c *Controller)Agents()([]Agent,error){jobs,err:=c.Jobs(1000);nodes:=c.registry.Nodes();out:=[]Agent{};for _,n:=range nodes{for slot:=1;slot<=n.MaxWorkers;slot++{a:=Agent{NodeID:n.NodeID,Machine:n.Machine,Slot:slot};for _,cj:=range jobs{j:=cj.Job;if cj.NodeID==n.NodeID&&j.AgentSlot==slot&&(j.Status==model.StatusRunning||j.Status==model.StatusStarting){a.Busy=true;a.JobID=j.JobID;a.Status=j.Status;break}};out=append(out,a)}};return out,err}
func(c *Controller)JobStatus(jobID string)(ClusterJob,error){jobID=strings.TrimSpace(jobID);if jobID==""{return ClusterJob{},errors.New("job_id required")};for _,n:=range c.registry.Nodes(){if !n.Online{continue};resp,err:=c.client.Get(strings.TrimRight(n.Endpoint,"/")+"/v1/jobs/"+url.PathEscape(jobID));if err!=nil{continue};if resp.StatusCode==http.StatusNotFound{resp.Body.Close();continue};if resp.StatusCode/100!=2{resp.Body.Close();continue};var j model.Job;err=json.NewDecoder(resp.Body).Decode(&j);resp.Body.Close();if err==nil{return ClusterJob{NodeID:n.NodeID,Endpoint:n.Endpoint,Job:j},nil}};return ClusterJob{},errors.New("job not found on online cluster nodes")}
func(c *Controller)Submit(req SubmitRequest)(SubmitResult,error){if req.Job.JobID==""||req.Job.DispatchID==""{return SubmitResult{},errors.New("job_id and dispatch_id required")};n,err:=c.registry.Select(req.Job.Machine,req.RequiredCapabilities);if err!=nil{return SubmitResult{},err};job:=req.Job;job.Machine=n.Machine;b,err:=json.Marshal(job);if err!=nil{return SubmitResult{},err};resp,err:=postJSON(c.client,strings.TrimRight(n.Endpoint,"/")+"/v1/jobs",b);if err!=nil{return SubmitResult{},err};defer resp.Body.Close();if resp.StatusCode/100!=2{msg,_:=io.ReadAll(io.LimitReader(resp.Body,4096));return SubmitResult{},fmt.Errorf("remote submit %s: %s %s",n.NodeID,resp.Status,string(msg))};var ack model.SubmitAck;if err:=json.NewDecoder(resp.Body).Decode(&ack);err!=nil{return SubmitResult{},err};if !ack.Accepted||ack.JobID!=job.JobID||ack.DispatchID!=job.DispatchID{return SubmitResult{},errors.New("remote durable ACK mismatch")};return SubmitResult{Selected:n,Ack:ack},nil}
func(c *Controller)JobAction(jobID,action string)(ControlResult,error){if action!="cancel"&&action!="retry"{return ControlResult{},errors.New("action must be cancel or retry")};cj,err:=c.JobStatus(jobID);if err!=nil{return ControlResult{},err};u:=strings.TrimRight(cj.Endpoint,"/")+"/v1/jobs/"+url.PathEscape(jobID)+"/"+action;resp,err:=postJSON(c.client,u,nil);if err!=nil{return ControlResult{},err};defer resp.Body.Close();if resp.StatusCode/100!=2{msg,_:=io.ReadAll(io.LimitReader(resp.Body,4096));return ControlResult{},fmt.Errorf("remote %s %s: %s",action,cj.NodeID,string(msg))};var body any;if err:=json.NewDecoder(resp.Body).Decode(&body);err!=nil{return ControlResult{},err};return ControlResult{NodeID:cj.NodeID,Machine:cj.Job.Machine,Endpoint:cj.Endpoint,Action:action,Response:body},nil}
func(c *Controller)Drain(machine,mode string)([]ControlResult,error){if mode!="queued"&&mode!="all"{return nil,errors.New("mode must be queued or all")};machine=strings.TrimSpace(machine);if machine==""{return nil,errors.New("machine required; use a node id/machine or all")};targets:=[]Node{};if strings.EqualFold(machine,"all"){for _,n:=range c.registry.Nodes(){if n.Online{targets=append(targets,n)}}}else{n,err:=c.registry.Select(machine,nil);if err!=nil{return nil,err};targets=append(targets,n)};out:=[]ControlResult{};for _,n:=range targets{u:=strings.TrimRight(n.Endpoint,"/")+"/v1/queue/drain?mode="+url.QueryEscape(mode);resp,err:=postJSON(c.client,u,nil);if err!=nil{return out,err};var body any;if resp.StatusCode/100==2{err=json.NewDecoder(resp.Body).Decode(&body)}else{msg,_:=io.ReadAll(io.LimitReader(resp.Body,4096));err=fmt.Errorf("remote drain %s: %s",n.NodeID,string(msg))};resp.Body.Close();if err!=nil{return out,err};out=append(out,ControlResult{NodeID:n.NodeID,Machine:n.Machine,Endpoint:n.Endpoint,Action:"drain."+mode,Response:body})};return out,nil}
func postJSON(c *http.Client,u string,b []byte)(*http.Response,error){if b==nil{b=[]byte(`{}`)};req,err:=http.NewRequest(http.MethodPost,u,bytes.NewReader(b));if err!=nil{return nil,err};req.Header.Set("Content-Type","application/json");return c.Do(req)}
func(c *Controller)JobCounts()map[string]any{jobs,_:=c.Jobs(1000);counts:=map[string]int{};for _,j:=range jobs{counts[string(j.Job.Status)]++};return map[string]any{"total":len(jobs),"by_status":counts,"observed_at":time.Now().UTC()}}
