package cluster

import(
 "encoding/json";"errors";"net/http";"sort";"strings";"sync";"time"
)
type ServiceStatus struct{RunningCommit string `json:"running_commit"`;TargetCommit string `json:"target_commit"`;UpgradeStatus string `json:"upgrade_status"`;UpgradeVerified bool `json:"upgrade_verified"`;ServiceStartedAt time.Time `json:"service_started_at"`;SupervisorAPIVersion string `json:"supervisor_api_version"`}
type Node struct{NodeID string `json:"node_id"`;Machine string `json:"machine"`;Endpoint string `json:"endpoint"`;Online bool `json:"online"`;HeartbeatAt time.Time `json:"heartbeat_at"`;LeaseUntil time.Time `json:"lease_until"`;MaxWorkers int `json:"max_workers"`;BusyWorkers int `json:"busy_workers"`;FreeWorkers int `json:"free_workers"`;QueuedJobs int `json:"queued_jobs"`;Capabilities []string `json:"capabilities"`;Inventory any `json:"inventory,omitempty"`;Build any `json:"build,omitempty"`;Service ServiceStatus `json:"service"`;LastError string `json:"last_error,omitempty"`}
type Registry struct{mu sync.RWMutex;nodes map[string]Node}
func NewRegistry()*Registry{return &Registry{nodes:map[string]Node{}}}
func key(s string)string{return strings.ToLower(strings.TrimSpace(s))}
func(r *Registry)Upsert(n Node){r.mu.Lock();defer r.mu.Unlock();if n.NodeID==""{n.NodeID=key(n.Machine)};r.nodes[key(n.NodeID)]=n}
func(r *Registry)Nodes()[]Node{r.mu.RLock();defer r.mu.RUnlock();now:=time.Now().UTC();out:=make([]Node,0,len(r.nodes));for _,n:=range r.nodes{n.Online=n.LastError==""&&n.LeaseUntil.After(now);out=append(out,n)};sort.Slice(out,func(i,j int)bool{return out[i].NodeID<out[j].NodeID});return out}
func(r *Registry)Select(machine string,required []string)(Node,error){nodes:=r.Nodes();want:=key(machine);candidates:=[]Node{};for _,n:=range nodes{if !n.Online{continue};if want!=""&&want!="any"&&key(n.Machine)!=want&&key(n.NodeID)!=want{continue};if !hasAll(n.Capabilities,required){continue};candidates=append(candidates,n)};if len(candidates)==0{return Node{},errors.New("no online compatible node")};sort.SliceStable(candidates,func(i,j int)bool{if candidates[i].FreeWorkers==candidates[j].FreeWorkers{return candidates[i].QueuedJobs<candidates[j].QueuedJobs};return candidates[i].FreeWorkers>candidates[j].FreeWorkers});return candidates[0],nil}
func hasAll(have,need []string)bool{m:=map[string]bool{};for _,x:=range have{m[key(x)]=true};for _,x:=range need{if !m[key(x)]{return false}};return true}
type statusEnvelope struct{NodeID string `json:"node_id"`;Machine string `json:"machine"`;Advertise string `json:"advertise_endpoint"`;HeartbeatAt time.Time `json:"heartbeat_at"`;LeaseUntil time.Time `json:"lease_until"`;MaxWorkers int `json:"max_workers"`;BusyWorkers int `json:"busy_workers"`;FreeWorkers int `json:"free_workers"`;QueuedJobs int `json:"queued_jobs"`;Inventory struct{Capabilities []string `json:"capabilities"`} `json:"inventory"`;Build any `json:"build"`;Service ServiceStatus `json:"service"`}
func Probe(client *http.Client,endpoint string)(Node,error){if client==nil{client=&http.Client{Timeout:3*time.Second}};source:=strings.TrimRight(endpoint,"/");resp,err:=client.Get(source+"/v1/node/status");if err!=nil{return Node{Endpoint:source,LastError:err.Error()},err};defer resp.Body.Close();if resp.StatusCode/100!=2{return Node{Endpoint:source,LastError:resp.Status},errors.New(resp.Status)};var s statusEnvelope;if err:=json.NewDecoder(resp.Body).Decode(&s);err!=nil{return Node{Endpoint:source,LastError:err.Error()},err};advertise:=strings.TrimRight(strings.TrimSpace(s.Advertise),"/");if advertise==""{advertise=source};return Node{NodeID:s.NodeID,Machine:s.Machine,Endpoint:advertise,Online:true,HeartbeatAt:s.HeartbeatAt,LeaseUntil:s.LeaseUntil,MaxWorkers:s.MaxWorkers,BusyWorkers:s.BusyWorkers,FreeWorkers:s.FreeWorkers,QueuedJobs:s.QueuedJobs,Capabilities:s.Inventory.Capabilities,Inventory:s.Inventory,Build:s.Build,Service:s.Service},nil}
