package api

import "net/http"

const dashboardHTML = `<!doctype html><html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>DirectWork</title><style>body{font-family:system-ui,-apple-system,Segoe UI,sans-serif;margin:0;background:#0b1020;color:#e8edf7}.wrap{max-width:1400px;margin:auto;padding:24px}.top{display:flex;justify-content:space-between;gap:16px;align-items:center}.brand{font-size:26px;font-weight:700}.muted{color:#98a5bc}.card{background:#131a2c;border:1px solid #263149;border-radius:14px;padding:16px;margin-top:16px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:12px}.pill{display:inline-block;border:1px solid #3b4865;border-radius:999px;padding:6px 10px;margin:3px}.ok{color:#6ee7a5}.bad{color:#ff8c8c}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:10px;border-bottom:1px solid #25314a;vertical-align:top}button{background:#26385f;color:#fff;border:0;border-radius:8px;padding:7px 10px;cursor:pointer}a{color:#8ec5ff}.art{margin:8px 0;padding:10px;border:1px solid #2b3853;border-radius:10px}</style></head><body><div class="wrap"><div class="top"><div><div class="brand">DirectWork</div><div class="muted">密語驅動的本機工作總控</div></div><div id="ver" class="pill">版本檢查中…</div></div><div id="node" class="card">載入節點狀態…</div><div class="card"><div class="top"><b>Durable Work</b><button onclick="refreshAll()">重新整理</button></div><div style="overflow:auto"><table><thead><tr><th>Work</th><th>Project/Case</th><th>Status</th><th>Slot/PID</th><th>CWD</th><th>成果</th></tr></thead><tbody id="works"></tbody></table></div></div><div class="card"><b>成果瀏覽</b><div id="arts" class="muted" style="margin-top:10px">點選工作成果。</div></div></div><script>
async function getJSON(u,o){var r=await fetch(u,o);if(!r.ok)throw Error(await r.text());return r.json()}
function esc(x){return String(x==null?'':x).replace(/[&<>"']/g,function(m){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]})}
async function loadNode(){try{var n=await getJSON('/v1/node/status');document.getElementById('ver').textContent=(n.version||'dev')+' · '+String(n.commit||'unknown').slice(0,8);document.getElementById('node').innerHTML='<div class="grid"><div><b>'+esc(n.machine)+'</b><div class="muted">Machine</div></div><div><b>'+n.busy_workers+'/'+n.max_workers+'</b><div class="muted">Busy Slots</div></div><div><b>'+n.queued_works+'</b><div class="muted">Pending</div></div><div><b class="ok">ONLINE</b><div class="muted">'+esc(n.advertise||'')+'</div></div></div>'}catch(e){document.getElementById('node').innerHTML='<span class="bad">節點狀態讀取失敗</span>'}}
async function loadWorks(){try{var d=await getJSON('/v1/work?limit=200'),tb=document.getElementById('works');tb.innerHTML='';d.works.forEach(function(x){var tr=document.createElement('tr');tr.innerHTML='<td><b>'+esc(x.work_id)+'</b><div class="muted">'+esc(x.dispatch_id||'')+'</div></td><td>'+esc(x.project||'')+'<div class="muted">'+esc(x.case_id||'')+'</div></td><td>'+esc(x.status)+'</td><td>'+(x.slot||'-')+' / '+(x.pid||'-')+'</td><td>'+esc(x.cwd)+'</td><td><button>瀏覽</button></td>';tr.querySelector('button').onclick=function(){loadArtifacts(x.work_id)};tb.appendChild(tr)})}catch(e){}}
async function loadArtifacts(id){var box=document.getElementById('arts');box.textContent='讀取中…';try{var d=await getJSON('/v1/work/'+encodeURIComponent(id)+'/artifacts');box.innerHTML='';d.artifacts.forEach(function(a){var v=document.createElement('div');v.className='art';v.innerHTML='<b>'+esc(a.kind)+'</b> · '+a.size+' bytes<br><a target="_blank" href="'+esc(a.url)+'">'+esc(a.relative_path)+'</a><div class="muted">SHA256 '+esc(a.sha256||'skipped')+'</div>';box.appendChild(v)});if(!d.artifacts.length)box.textContent='目前沒有可瀏覽成果'}catch(e){box.textContent='成果讀取失敗'}}
async function refreshAll(){await loadNode();await loadWorks()}refreshAll();setInterval(refreshAll,5000)
</script></body></html>`

func(s *Server)dashboard(w http.ResponseWriter,r *http.Request){w.Header().Set("Content-Type","text/html; charset=utf-8");_,_=w.Write([]byte(dashboardHTML))}
