param(
    [string]$Workspace = 'D:\AI-Work\jobs\0005-SNOW-WHITE',
    [string]$OpenWorkerRoot = '',
    [string]$GoToolRoot = '',
    [string]$EngineeringOSRoot = '',
    [string]$PythonExe = '',
    [switch]$SkipCodeSync
)
$ErrorActionPreference='Stop';$expectedHost='DESKTOP-ODAQN0D';$actualHost=[Environment]::MachineName;if($actualHost-ine$expectedHost){throw "Case 0005 must activate on $expectedHost; actual=$actualHost"}
function Resolve-RepoRoot{param([string]$Explicit,[string[]]$Candidates,[string[]]$Markers,[string]$Name);$items=@();if(-not[string]::IsNullOrWhiteSpace($Explicit)){$items+=$Explicit};$items+=$Candidates;foreach($candidate in $items){if([string]::IsNullOrWhiteSpace($candidate)){continue};try{$root=(Resolve-Path -LiteralPath $candidate -ErrorAction Stop).Path}catch{continue};$valid=$true;foreach($marker in $Markers){if(-not(Test-Path -LiteralPath(Join-Path $root $marker)-PathType Leaf)){$valid=$false;break}};if($valid){return $root}};throw "$Name checkout not found"}
function Resolve-Python([string]$Explicit){$c=@();if(-not[string]::IsNullOrWhiteSpace($Explicit)){$c+=$Explicit};$c+=@('C:\Python314\python.exe','C:\Python313\python.exe','C:\Python312\python.exe','C:\Python311\python.exe','C:\Python310\python.exe');foreach($p in $c){if(Test-Path -LiteralPath $p -PathType Leaf){return(Resolve-Path -LiteralPath $p).Path}};$cmd=Get-Command python.exe -ErrorAction SilentlyContinue;if($null-ne$cmd){return$cmd.Source};throw'Python executable not found'}
$OpenWorkerRoot=Resolve-RepoRoot $OpenWorkerRoot @('C:\github-runners\openworker\_work\openworker\openworker','D:\AI\openworker','D:\AIWork\openworker','D:\PyWork\openworker') @('case-specs\0005.json','coworker\case0005_verified_local_controller.py') 'OpenWorker';$GoToolRoot=Resolve-RepoRoot $GoToolRoot @('C:\github-runners\go-tool-runtime\_work\go-tool-runtime\go-tool-runtime','D:\AI\go-tool-runtime','D:\AIWork\go-tool-runtime','D:\PyWork\go-tool-runtime') @('go.mod','scripts\windows\install-and-verify-true-local-supervisor.ps1') 'go-tool-runtime';$EngineeringOSRoot=Resolve-RepoRoot $EngineeringOSRoot @('C:\github-runners\AI-Engineering-OS\_work\AI-Engineering-OS\AI-Engineering-OS','D:\AI\AI-Engineering-OS','D:\AIWork\AI-Engineering-OS','D:\PyWork\AI-Engineering-OS') @('go.mod','AI-Engineering-OS.bat') 'AI-Engineering-OS';$PythonExe=Resolve-Python $PythonExe
if(-not$SkipCodeSync){foreach($repo in @($GoToolRoot,$OpenWorkerRoot,$EngineeringOSRoot)){if(Test-Path(Join-Path $repo '.git')){Push-Location $repo;try{$dirty=&git status --porcelain;if($LASTEXITCODE-ne0){throw'git status failed'};if($dirty){throw "refuse code sync on dirty checkout: $repo"};&git pull --ff-only origin main;if($LASTEXITCODE-ne0){throw "git pull failed: $repo"}}finally{Pop-Location}}}}
& powershell.exe -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Bypass -File (Join-Path $OpenWorkerRoot 'scripts\openworker_set_machine_roots.ps1') -OpenWorkerRoot $OpenWorkerRoot -GoToolRoot $GoToolRoot -EngineeringOSRoot $EngineeringOSRoot;if($LASTEXITCODE-ne0){throw'machine-root authority update failed'}
$installRoot="$env:ProgramData\go-tool-runtime\work-agent";$realReceipt=Join-Path $installRoot 'true-local-supervisor-real-verification.json';& powershell.exe -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Bypass -File (Join-Path $GoToolRoot 'scripts\windows\install-and-verify-true-local-supervisor.ps1') -MaxParallelActions 4 -InstallRoot $installRoot -OpenWorkerRoot $OpenWorkerRoot -EngineeringOSRoot $EngineeringOSRoot;if($LASTEXITCODE-ne0){throw'true local supervisor install/REAL verification failed'}
$status=Invoke-RestMethod -Method Get -Uri "http://127.0.0.1:8848/api/execution/local-supervisor/status?machine=$expectedHost&limit=200" -TimeoutSec 10;if([string]$status.status-ne'OPERATIONAL'-or-not[bool]$status.operational){throw'local supervisor is not OPERATIONAL'};if([string]$status.verification.status-ne'REAL_VERIFIED'){throw'local supervisor is not REAL_VERIFIED'};if([int]$status.fresh_claim_slot_count-lt4-or[int]$status.fresh_executor_slot_count-lt4){throw'need fresh 4+4 slots'};if([string]$status.route_label-ne'LOCAL_SUPERVISOR'){throw'unexpected route'};if([bool]$status.github_action_used_for_business_execution){throw'GitHub business execution forbidden'};if(-not(Test-Path $realReceipt)){throw'REAL verification receipt missing'}
$requiredCapabilities=@('comfyx-studio.director.preproduction','comfyx-studio.storyboard.plan','presentation.openmaic','openworker.case.publish-artifacts','openworker.review.await-drive','image.comfyx.storyboard-real','comfyx-studio.storyboard.real-bind','comfyx.production.video.real','comfyx-studio.finalize','openworker.workledger.revision','engineering_os.case0005.identity','engineering_os.artifact.register','engineering_os.delivery.publish','openworker.delivery.validate','drive.review.publish');$registered=@($status.registered_capabilities|%{[string]$_});$missing=@($requiredCapabilities|?{$registered-notcontains$_});if($missing.Count){throw('Case capability coverage incomplete: '+($missing-join', '))}
# Install the CLI-neutral control surface consumed by OpenCode/Codex/other local agents.
$ctlInstall=Join-Path $OpenWorkerRoot 'scripts\install-openworkerctl.ps1';$ctlInstallJSON=& powershell.exe -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Bypass -File $ctlInstall;if($LASTEXITCODE-ne0){throw'openworkerctl install failed'};$ctlInstallReceipt=($ctlInstallJSON|Out-String).Trim()|ConvertFrom-Json;$ctl=[string]$ctlInstallReceipt.exe;if(-not(Test-Path -LiteralPath $ctl -PathType Leaf)){throw'openworkerctl executable missing after install'}
New-Item -ItemType Directory -Force -Path $Workspace|Out-Null;$specPath=Join-Path $OpenWorkerRoot 'case-specs\0005.json';$manifestPath=Join-Path $OpenWorkerRoot 'case-worklists\0005.json';$controllerModule='coworker.case0005_verified_local_controller';$bootstrap=[ordered]@{case_id='0005';machine=$expectedHost;workspace_root=$Workspace;openworker_root=$OpenWorkerRoot;controller_module=$controllerModule;manifest_path=$manifestPath;spec_path=$specPath;python_exe=$PythonExe;env=[ordered]@{GTR_WORK_QUEUE_URL='http://127.0.0.1:8848';GTR_LOCAL_WORKERS='4';OPENWORKER_ROOT=$OpenWorkerRoot;GO_TOOL_ROOT=$GoToolRoot;ENGINEERING_OS_ROOT=$EngineeringOSRoot;GTR_LOCAL_EXEC_EXE=(Join-Path $installRoot 'gtr-local-exec.exe')}};$bootstrapAck=Invoke-RestMethod -Method Post -Uri 'http://127.0.0.1:8848/api/openworker/case/bootstrap' -ContentType'application/json' -Body($bootstrap|ConvertTo-Json -Depth 8 -Compress)-TimeoutSec 60;if([string]$bootstrapAck.status-ne'completed'){throw'Case bootstrap failed'}
$runtime=$null;$routeProven=$false;$deadline=[DateTime]::UtcNow.AddSeconds(90);while([DateTime]::UtcNow-lt$deadline){try{$runtime=Invoke-RestMethod -Method Get -Uri "http://127.0.0.1:8848/api/openworker/case/runtime?case_id=0005&machine=$expectedHost&limit=500" -TimeoutSec 5;if([bool]$runtime.route_resolved_from_local_evidence-and[string]$runtime.route_label-eq'LOCAL_SUPERVISOR'){$routeProven=$true;break}}catch{};Start-Sleep -Milliseconds 500};if(-not$routeProven){throw'Case did not materialize LOCAL_SUPERVISOR route evidence'}
$controlDir=Join-Path $Workspace '.openworker';New-Item -ItemType Directory -Force -Path $controlDir|Out-Null;$receiptPath=Join-Path $controlDir 'true-local-supervisor-activation.json';$receipt=[ordered]@{schema_version='openworker-case0005-true-local-activation/v7';status='OPERATIONAL';case_id='0005';machine=$actualHost;workspace_root=$Workspace;controller_module=$controllerModule;openworkerctl=$ctl;openworkerctl_installed=$true;opencode_control_surface='openworkerctl';business_execution_authority='go-tool-runtime-local-supervisor';local_queue='go-tool-runtime:8848';max_parallel_actions=4;fresh_claim_slot_count=[int]$status.fresh_claim_slot_count;fresh_executor_slot_count=[int]$status.fresh_executor_slot_count;registered_capabilities=$registered;required_case_capabilities=$requiredCapabilities;capability_coverage_complete=$true;github_action_used_for_business_execution=$false;binaries_reinstalled_from_current_checkout=$true;real_verification_receipt=$realReceipt;supervisor_status=$status;bootstrap_ack=$bootstrapAck;initial_case_runtime=$runtime;activated_at=[DateTime]::UtcNow.ToString('o')};$temp="$receiptPath.tmp";[IO.File]::WriteAllText($temp,($receipt|ConvertTo-Json -Depth 20),[Text.UTF8Encoding]::new($false));Move-Item $temp $receiptPath -Force;Write-Host "CASE0005_TRUE_LOCAL_SUPERVISOR_OPERATIONAL host=$actualHost ctl=$ctl receipt=$receiptPath"
