param(
  [string]$OpenWorkerUrl='http://127.0.0.1:8787',
  [string]$WorkspaceRoot='D:\AI-Work\jobs\0003-YUJING-BRIDGE',
  [string]$Machine='DESKTOP-UL7V2VV',
  [string]$OpenWorkerRoot=$env:OPENWORKER_ROOT,
  [string]$DriveSyncRoot=$env:OPENWORKER_REVIEW_DRIVE_ROOT,
  [string]$GoToolRoot=$env:GO_TOOL_ROOT,
  [string]$TerrainRoot=$env:TERRAIN_ROOT,
  [string]$SceneXRoot=$env:SCENEX_ROOT,
  [string]$EngineeringOSRoot=$env:ENGINEERING_OS_ROOT,
  [string]$OSProjectId=$env:ENGINEERING_OS_PROJECT_ID,
  [string]$OSJobId=$env:ENGINEERING_OS_JOB_ID,
  [string]$EngineeringOSBaseUrl='http://127.0.0.1:8080',
  [string]$CatalogPath='D:\TaiwanDTM\catalog\dtm_catalog.sqlite'
)
$ErrorActionPreference='Stop'
if(-not $env:COMPUTERNAME.Equals($Machine,[StringComparison]::OrdinalIgnoreCase)){throw "wrong host expected=$Machine actual=$env:COMPUTERNAME"}
if([string]::IsNullOrWhiteSpace($GoToolRoot)){throw 'GO_TOOL_ROOT/GoToolRoot is required'}
if([string]::IsNullOrWhiteSpace($TerrainRoot)){throw 'TERRAIN_ROOT/TerrainRoot is required'}
$scriptRoot=Split-Path -Parent $MyInvocation.MyCommand.Path
$evidenceDir=Join-Path $WorkspaceRoot 'evidence';New-Item -ItemType Directory -Force -Path $evidenceDir|Out-Null
function Read-Json([string]$Path){if(-not(Test-Path -LiteralPath $Path)){return $null};try{return Get-Content -LiteralPath $Path -Raw|ConvertFrom-Json}catch{return $null}}
function File-OK([string]$Path){return (Test-Path -LiteralPath $Path) -and (-not (Get-Item -LiteralPath $Path).PSIsContainer) -and ((Get-Item -LiteralPath $Path).Length -gt 0)}
function SHA-OK([string]$Path,[string]$Expected){if(-not(File-OK $Path) -or [string]::IsNullOrWhiteSpace($Expected)){return $false};$want=$Expected.ToLowerInvariant().Replace('sha256:','');return ((Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant() -eq $want)}
$acceptedGeo=Read-Json (Join-Path $WorkspaceRoot 'geo\geolocation.json')
if($null -eq $acceptedGeo -or -not $acceptedGeo.ok){throw 'accepted geolocation missing/not ok'}
$acceptedLat=[double]$acceptedGeo.geolocation.lat;$acceptedLng=[double]$acceptedGeo.geolocation.lng
function Geo-OK($g){if($null -eq $g){return $false};return ([math]::Abs(([double]$g.lat)-$acceptedLat) -le 0.0000001) -and ([math]::Abs(([double]$g.lng)-$acceptedLng) -le 0.0000001)}
function StreetView-OK{
  $m=Read-Json (Join-Path $WorkspaceRoot 'streetview\browser\streetview-browser-screenshots.json')
  if($null -eq $m -or -not $m.ok -or $m.schema_version -ne 'streetview-browser-screenshots/v3' -or [string]$m.transport -ne 'localexec'){return $false}
  if(-not ([string]$m.assigned_host).Equals($Machine,[StringComparison]::OrdinalIgnoreCase) -or -not(Geo-OK $m.geolocation)){return $false}
  $r=@($m.renders);if($r.Count -ne 4){return $false};$seen=@{}
  foreach($x in $r){$heading=[string]$x.heading;if($heading -notin @('0','90','180','270') -or $seen.ContainsKey($heading)){return $false};$seen[$heading]=$true;$receipt=$x.receipt;if($null -eq $receipt -or -not $receipt.ok){return $false};if([string]$receipt.provider -ne 'google' -or [string]$receipt.mode -ne 'headless-render-webgl' -or [string]$receipt.backend -ne 'angle-swiftshader-webgl'){return $false};if([int]$receipt.width -ne 1920 -or [int]$receipt.height -ne 1080 -or [int64]$receipt.bytes -le 0){return $false};$path=[string]$x.path;if([string]::IsNullOrWhiteSpace($path) -or -not(SHA-OK $path ([string]$receipt.sha256)){return $false};if([string]$receipt.output -and -not ([string]$receipt.output).Equals($path,[StringComparison]::OrdinalIgnoreCase)){return $false}}
  return $seen.Count -eq 4
}
function Ortho-OK{
  $m=Read-Json (Join-Path $WorkspaceRoot 'orthophoto\nlsc-photo2\orthophoto-photo2-workspace.json')
  if($null -eq $m -or -not $m.ok -or [string]$m.schema_version -ne 'orthophoto-workspace/v2' -or [string]$m.transport -ne 'localexec'){return $false};if(-not ([string]$m.assigned_host).Equals($Machine,[StringComparison]::OrdinalIgnoreCase) -or -not(Geo-OK $m.geolocation)){return $false}
  $r=$m.producer_receipt;if($null -eq $r -or -not $r.ok -or [string]$r.schema_version -ne 'orthophoto-nlsc-photo2/v1'){return $false};if([string]$r.plan.provider -ne 'nlsc' -or [string]$r.plan.layer -ne 'PHOTO2' -or [int]$r.plan.zoom -ne 19){return $false};if([math]::Abs(([double]$r.plan.latitude)-$acceptedLat) -gt 0.0000001 -or [math]::Abs(([double]$r.plan.longitude)-$acceptedLng) -gt 0.0000001){return $false};if([int]$r.plan.tile_count -lt 1 -or [int]$r.plan.tile_count -gt 25){return $false};if($null -eq $r.visibility -or -not [bool]$r.visibility.visible){return $false};if([double]$r.visibility.useful_pixel_ratio -lt 0.20 -or [double]$r.visibility.luma_stddev -lt 0.02 -or [double]$r.visibility.luma_range -lt 0.10){return $false};$image=[string]$m.image;if([string]::IsNullOrWhiteSpace($image) -or -not(SHA-OK $image ([string]$r.output_sha256)){return $false};if([string]$r.output_path -and -not ([string]$r.output_path).Equals($image,[StringComparison]::OrdinalIgnoreCase)){return $false};if([int64]$r.output_bytes -le 0 -or [int]$r.image_width -le 0 -or [int]$r.image_height -le 0){return $false};return File-OK ([string]$m.evidence)
}
function Terrain-OK{$root=Join-Path $WorkspaceRoot 'terrain';$names=@('terrain-context.json','terrain-build.json','terrain-grid.json','terrain.dxf','terrain-heightmap.raw','terrain-heightmap.json','terrain.obj','terrain-mesh.json','terrain-scene.json','scenex-terrain-scene.json');foreach($n in $names){if(-not(File-OK (Join-Path $root $n))){return $false}};$c=Read-Json (Join-Path $root 'terrain-context.json');return $null -ne $c -and [int]$c.usable_tiles -gt 0}
function Consumer-OK{$root=Join-Path $WorkspaceRoot 'consumer';$names=@('visual-frame-set.json','blender-reference-pack.json','minimax-h3-reference-pack.json','blender-visual-handoff.json','minimax-h3-visual-handoff.json','geo-context.json','consumer-orchestration.json');foreach($n in $names){if(-not(File-OK (Join-Path $root $n))){return $false}};$c=Read-Json (Join-Path $root 'consumer-orchestration.json');return $null -ne $c -and $c.schema_version -eq 'consumer-orchestration/v1'}
function Blender-OK{$root=Join-Path $WorkspaceRoot 'blender';foreach($n in @('terrain-scene.blend','terrain-render.png','blender-execution-request.json','blender-scene-evidence.json','blender-render-handoff.json')){if(-not(File-OK (Join-Path $root $n))){return $false}};$e=Read-Json (Join-Path $root 'blender-scene-evidence.json');$h=Read-Json (Join-Path $root 'blender-render-handoff.json');return $null -ne $e -and $null -ne $h -and $e.schema_version -eq 'blender-scene-evidence/v1' -and $h.schema_version -eq 'blender-render-handoff/v1'}
function SceneX-OK{$root=Join-Path $WorkspaceRoot 'scenex';$m=Read-Json (Join-Path $root 'scenex-workspace.json');if($null -eq $m -or -not $m.ok -or $m.schema_version -ne 'scenex-workspace-browse/v1'){return $false};if([int]$m.active_chunks -le 0 -or [int]$m.terrain_geometry_count -le 0){return $false};if(-not(SHA-OK ([string]$m.screenshot.path) ([string]$m.screenshot.sha256))){return $false};if(-not(SHA-OK ([string]$m.region_pack.path) ([string]$m.region_pack.sha256))){return $false};if(-not(SHA-OK ([string]$m.evidence.path) ([string]$m.evidence.sha256))){return $false};return $true}
function OSArtifacts-OK{
  $r=Read-Json (Join-Path $evidenceDir 'case0003-os-artifact-ingest-receipt.json');if($null -eq $r -or -not $r.ok -or $r.schema_version -ne 'engineering-os-artifact-ingest-receipt/v1'){return $false}
  if(-not [string]::IsNullOrWhiteSpace($OSProjectId) -and [string]$r.project_id -ne $OSProjectId){return $false};if(-not [string]::IsNullOrWhiteSpace($OSJobId) -and [string]$r.job_id -ne $OSJobId){return $false}
  $expected=[ordered]@{'terrain_context'='terrain\terrain-context.json';'terrain_grid'='terrain\terrain-grid.json';'terrain_mesh_obj'='terrain\terrain.obj';'terrain_scene'='terrain\terrain-scene.json';'terrain_blender_scene'='blender\terrain-scene.blend';'terrain_blender_render_png'='blender\terrain-render.png';'terrain_blender_evidence'='blender\blender-scene-evidence.json';'scenex_terrain_region_pack'='scenex\terrain.region.json';'scenex_terrain_browse_png'='scenex\terrain-browse.png';'scenex_terrain_browse_evidence'='scenex\terrain-browse-evidence.json';'scenex_workspace_manifest'='scenex\scenex-workspace.json'}
  $arts=@($r.artifacts);if($arts.Count -lt $expected.Count){return $false};foreach($kind in $expected.Keys){$a=@($arts|Where-Object{[string]$_.kind -eq $kind}|Select-Object -Last 1);if($a.Count -ne 1){return $false};if(-not(SHA-OK (Join-Path $WorkspaceRoot $expected[$kind]) ([string]$a[0].checksum)){return $false}};return $true
}
function OSApproval-OK{if([string]::IsNullOrWhiteSpace($OSJobId)){return $false};try{$a=Invoke-RestMethod -Method Get -Uri ($EngineeringOSBaseUrl.TrimEnd('/')+"/api/v1/jobs/$OSJobId/approval-status") -TimeoutSec 5;return [bool]$a.approved}catch{return $false}}
function OSDelivery-OK{if([string]::IsNullOrWhiteSpace($OSJobId)){return $false};try{$d=Invoke-RestMethod -Method Get -Uri ($EngineeringOSBaseUrl.TrimEnd('/')+"/api/v1/jobs/$OSJobId/deliveries/latest") -TimeoutSec 5;if([string]$d.status -ne 'published'){return $false};if(-not(File-OK ([string]$d.manifest_path)) -or -not(File-OK ([string]$d.website_entry))){return $false};$m=Read-Json ([string]$d.manifest_path);return $null -ne $m -and $m.schema_version -eq 'delivery-manifest/1.0' -and [string]$m.job_id -eq $OSJobId -and [int64]$m.revision -eq [int64]$d.revision}catch{return $false}}
function DriveReview-OK{
  $r=Read-Json (Join-Path $WorkspaceRoot 'acceptance\openworker-final\drive-review-prepare.json');if($null -eq $r -or [string]$r.schema_version -ne 'openworker-case0003-drive-review-prepare/v2' -or [string]$r.status -ne 'WAITING_DRIVE_REVIEW'){return $false}
  $rid=[string]$r.revision_id;if([string]::IsNullOrWhiteSpace($rid)){return $false};$manifest=Join-Path $WorkspaceRoot ('.openworker\reviews\'+$rid+'\manifest.json');if(-not(SHA-OK $manifest ([string]$r.bundle_manifest_sha256)){return $false};if(-not(SHA-OK ([string]$r.review_zip_path) ([string]$r.review_zip_sha256)){return $false};if(-not(SHA-OK ([string]$r.drive_sync_zip_target) ([string]$r.review_zip_sha256)){return $false};return $true
}
function DriveReceipt-OK{
  $d=Read-Json (Join-Path $WorkspaceRoot 'acceptance\openworker-final\drive-review-prepare.json');if($null -eq $d -or [string]$d.schema_version -ne 'openworker-case0003-drive-review-prepare/v2'){return $false};$p=Join-Path ([string]$d.drive_sync_target) 'connector-review-receipt.json';$r=Read-Json $p;if($null -eq $r){return $false};if([string]$r.transport -ne 'google-drive-connector' -or [string]$r.revision_id -ne [string]$d.revision_id){return $false};if([string]$r.bundle_manifest_sha256 -ne [string]$d.bundle_manifest_sha256){return $false};$c=$r.cloud_publication;if($null -eq $c){return $false};return -not[string]::IsNullOrWhiteSpace([string]$c.drive_revision_folder_id) -and -not[string]::IsNullOrWhiteSpace([string]$c.drive_zip_file_id) -and [string]$c.review_zip_sha256 -eq [string]$d.review_zip_sha256 -and [string]$c.bundle_manifest_sha256 -eq [string]$d.bundle_manifest_sha256
}
function ConnectorReview-OK{
  $drive=Read-Json (Join-Path $WorkspaceRoot 'acceptance\openworker-final\drive-review-prepare.json');$r=Read-Json (Join-Path $WorkspaceRoot 'acceptance\openworker-final\connector-review-apply.json')
  if($null -eq $drive -or $null -eq $r){return $false};return [string]$r.schema_version -eq 'openworker-case0003-connector-review-apply/v3' -and [string]$r.verdict -eq 'PASS' -and [string]$r.status -eq 'ACCEPTED_PENDING_FINALIZE' -and [string]$r.revision_id -eq [string]$drive.revision_id -and [string]$r.accepted_revision_id -eq [string]$drive.revision_id -and [string]$r.review_zip_sha256 -eq [string]$drive.review_zip_sha256
}
function Finalized-OK{
  $r=Read-Json (Join-Path $WorkspaceRoot 'acceptance\openworker-final\reviewed-delivery-finalize.json');if($null -eq $r){return $false};return [string]$r.schema_version -eq 'openworker-case0003-reviewed-delivery-finalize/v2' -and $r.ok -and [string]$r.status -eq 'DELIVERED' -and [string]$r.accepted_revision_id -eq [string]$r.revision_id -and [string]$r.delivered_revision_id -eq [string]$r.revision_id
}
function Gates{return [ordered]@{streetview=(StreetView-OK);orthophoto=(Ortho-OK);terrain=(Terrain-OK);consumer=(Consumer-OK);blender=(Blender-OK);scenex=(SceneX-OK);os_artifacts=(OSArtifacts-OK);os_approved=(OSApproval-OK);os_delivery=(OSDelivery-OK);drive_review=(DriveReview-OK);drive_receipt=(DriveReceipt-OK);connector_review_pass=(ConnectorReview-OK);finalized=(Finalized-OK)}}

$node=Invoke-RestMethod -Method Get -Uri "$OpenWorkerUrl/v1/node/status"
$agents=Invoke-RestMethod -Method Get -Uri "$OpenWorkerUrl/v1/cluster/agents"
$jobSnapshot=Invoke-RestMethod -Method Get -Uri "$OpenWorkerUrl/v1/jobs?limit=1000"
$activeStates=@('accepted','queued_local','starting','running')
function Active-Prefix([string]$Prefix){foreach($j in @($jobSnapshot.jobs)){if(([string]$j.job_id).StartsWith($Prefix,[StringComparison]::OrdinalIgnoreCase) -and $activeStates -contains [string]$j.status){return $true}};return $false}
$active=[ordered]@{streetview=(Active-Prefix 'case0003-streetview-');orthophoto=(Active-Prefix 'case0003-orthophoto-');terrain=(Active-Prefix 'case0003-terrain-aoi-');consumer=(Active-Prefix 'case0003-terrain-consumer-');blender=(Active-Prefix 'case0003-terrain-blender-');scenex=(Active-Prefix 'case0003-scenex-');os_artifacts=(Active-Prefix 'case0003-os-artifacts-');os_delivery=(Active-Prefix 'case0003-os-delivery-');drive_review=(Active-Prefix 'case0003-drive-review-');review_apply=(Active-Prefix 'case0003-review-apply-');finalize=(Active-Prefix 'case0003-review-finalize-')}
$before=Gates;$submitted=@();$suppressed=@()
if(-not($before.streetview -and $before.orthophoto)){if(($before.streetview -or -not $active.streetview) -and ($before.orthophoto -or -not $active.orthophoto)){& (Join-Path $scriptRoot 'case0003_local_imagery_parallel.ps1') -OpenWorkerUrl $OpenWorkerUrl -WorkspaceRoot $WorkspaceRoot -Machine $Machine -GoToolRoot $GoToolRoot -TerrainRoot $TerrainRoot;$submitted+='imagery_parallel'}else{$suppressed+='imagery_parallel_active'}}
if(-not $before.terrain){if($active.terrain){$suppressed+='terrain_aoi_active'}elseif(Test-Path -LiteralPath $CatalogPath){& (Join-Path $scriptRoot 'case0003_local_terrain_aoi.ps1') -OpenWorkerUrl $OpenWorkerUrl -WorkspaceRoot $WorkspaceRoot -Machine $Machine -GoToolRoot $GoToolRoot -TerrainRoot $TerrainRoot -CatalogPath $CatalogPath;$submitted+='terrain_aoi'}else{Write-Warning "DTM catalog missing; AOI not submitted: $CatalogPath"}}
$afterImmediate=Gates
if($afterImmediate.terrain -and -not $afterImmediate.scenex){if($active.scenex){$suppressed+='scenex_active'}elseif([string]::IsNullOrWhiteSpace($SceneXRoot)){Write-Warning 'SCENEX_ROOT missing; SceneX not submitted'}else{& (Join-Path $scriptRoot 'case0003_local_scenex.ps1') -OpenWorkerUrl $OpenWorkerUrl -WorkspaceRoot $WorkspaceRoot -Machine $Machine -GoToolRoot $GoToolRoot -SceneXRoot $SceneXRoot;$submitted+='scenex'}}
if($afterImmediate.streetview -and $afterImmediate.orthophoto -and $afterImmediate.terrain -and -not $afterImmediate.consumer){if($active.consumer){$suppressed+='consumer_active'}else{& (Join-Path $scriptRoot 'case0003_local_consumer.ps1') -OpenWorkerUrl $OpenWorkerUrl -WorkspaceRoot $WorkspaceRoot -Machine $Machine -GoToolRoot $GoToolRoot -TerrainRoot $TerrainRoot;$submitted+='consumer'}}
$afterConsumer=Gates
if($afterConsumer.consumer -and -not $afterConsumer.blender){if($active.blender){$suppressed+='blender_active'}else{& (Join-Path $scriptRoot 'case0003_local_blender.ps1') -OpenWorkerUrl $OpenWorkerUrl -WorkspaceRoot $WorkspaceRoot -Machine $Machine -GoToolRoot $GoToolRoot -TerrainRoot $TerrainRoot;$submitted+='blender'}}
$afterRender=Gates
if($afterRender.blender -and $afterRender.scenex -and -not $afterRender.os_artifacts){if($active.os_artifacts){$suppressed+='os_artifacts_active'}elseif([string]::IsNullOrWhiteSpace($EngineeringOSRoot) -or [string]::IsNullOrWhiteSpace($OSProjectId) -or [string]::IsNullOrWhiteSpace($OSJobId)){Write-Warning 'Engineering OS root/project/job identity missing; artifact ingest not submitted'}else{& (Join-Path $scriptRoot 'case0003_local_os_artifacts.ps1') -OpenWorkerUrl $OpenWorkerUrl -WorkspaceRoot $WorkspaceRoot -Machine $Machine -GoToolRoot $GoToolRoot -EngineeringOSRoot $EngineeringOSRoot -OSProjectId $OSProjectId -OSJobId $OSJobId;$submitted+='os_artifacts'}}
$afterRegistry=Gates
if($afterRegistry.os_artifacts -and $afterRegistry.os_approved -and -not $afterRegistry.os_delivery){if($active.os_delivery){$suppressed+='os_delivery_active'}elseif([string]::IsNullOrWhiteSpace($EngineeringOSRoot)){Write-Warning 'ENGINEERING_OS_ROOT missing; delivery not submitted'}else{& (Join-Path $scriptRoot 'case0003_local_os_delivery.ps1') -OpenWorkerUrl $OpenWorkerUrl -WorkspaceRoot $WorkspaceRoot -Machine $Machine -GoToolRoot $GoToolRoot -EngineeringOSRoot $EngineeringOSRoot -OSJobId $OSJobId -EngineeringOSBaseUrl $EngineeringOSBaseUrl;$submitted+='os_delivery'}}
$afterDelivery=Gates
if($afterDelivery.os_delivery -and -not $afterDelivery.drive_review){if($active.drive_review){$suppressed+='drive_review_active'}elseif([string]::IsNullOrWhiteSpace($OpenWorkerRoot) -or [string]::IsNullOrWhiteSpace($DriveSyncRoot)){Write-Warning 'OPENWORKER_ROOT / OPENWORKER_REVIEW_DRIVE_ROOT missing; Drive review prepare not submitted'}else{& (Join-Path $scriptRoot 'case0003_local_drive_review_prepare.ps1') -OpenWorkerUrl $OpenWorkerUrl -WorkspaceRoot $WorkspaceRoot -Machine $Machine -OpenWorkerRoot $OpenWorkerRoot -DriveSyncRoot $DriveSyncRoot;$submitted+='drive_review_prepare'}}
$afterDrive=Gates
if($afterDrive.drive_review -and $afterDrive.drive_receipt -and -not $afterDrive.connector_review_pass){if($active.review_apply){$suppressed+='review_apply_active'}elseif([string]::IsNullOrWhiteSpace($OpenWorkerRoot)){Write-Warning 'OPENWORKER_ROOT missing; connector review apply not submitted'}else{& (Join-Path $scriptRoot 'case0003_local_apply_drive_review.ps1') -OpenWorkerUrl $OpenWorkerUrl -WorkspaceRoot $WorkspaceRoot -Machine $Machine -OpenWorkerRoot $OpenWorkerRoot;$submitted+='connector_review_apply'}}
$afterReview=Gates
if($afterReview.connector_review_pass -and -not $afterReview.finalized){if($active.finalize){$suppressed+='review_finalize_active'}elseif([string]::IsNullOrWhiteSpace($OpenWorkerRoot)){Write-Warning 'OPENWORKER_ROOT missing; reviewed delivery finalizer not submitted'}else{& (Join-Path $scriptRoot 'case0003_local_finalize_reviewed_delivery.ps1') -OpenWorkerUrl $OpenWorkerUrl -WorkspaceRoot $WorkspaceRoot -Machine $Machine -OpenWorkerRoot $OpenWorkerRoot;$submitted+='reviewed_delivery_finalize'}}
$final=Gates
$next=if($final.finalized){'CASE0003_DELIVERED'}elseif($final.connector_review_pass){'REVIEWED_DELIVERY_FINALIZE_REQUIRED'}elseif($final.drive_receipt){'CONNECTOR_REVIEW_APPLY_REQUIRED'}elseif($final.drive_review){'CHATGPT_GOOGLE_DRIVE_CONNECTOR_REVIEW_REQUIRED'}elseif($final.os_delivery){'GOOGLE_DRIVE_REVIEW_PREPARE_REQUIRED'}elseif($final.os_artifacts -and -not $final.os_approved){'OS_REVIEW_APPROVAL_REQUIRED'}elseif($final.os_artifacts){'OS_DELIVERY_PUBLICATION_REQUIRED'}elseif($final.blender -and $final.scenex){'OS_ARTIFACT_REGISTRY_REQUIRED'}elseif($final.terrain){'SCENEX_CONSUMER_BLENDER_REAL_QC_REQUIRED'}else{'LOCAL_JOBS_AND_PHYSICAL_QC_REQUIRED'}
$receipt=[ordered]@{schema='openworker/case0003-local-continue/v10';case_id='0003';machine=$Machine;workspace_root=$WorkspaceRoot;transport='openworker-local-first';github_business_transport=$false;imagery_gate_contract='accepted-geo+sha+producer-provenance+semantic-visibility';accepted_geolocation=[ordered]@{lat=$acceptedLat;lng=$acceptedLng};checked_at=[DateTimeOffset]::UtcNow.ToString('o');node=$node;agents=$agents;active_stage_snapshot=$active;gates_before=$before;gates_after_submission=$final;submitted=$submitted;suppressed_duplicate_submissions=$suppressed;next_boundary=$next}
$path=Join-Path $evidenceDir 'case0003-local-continue.json';$receipt|ConvertTo-Json -Depth 12|Set-Content -LiteralPath $path -Encoding utf8;$receipt|ConvertTo-Json -Depth 12|Write-Host
