package api

import "net/http"

func (s *Server) dashboardV3(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	_, _ = w.Write([]byte(openworkerDashboardV3HTML))
}

const openworkerDashboardV3HTML = `<!doctype html>
<html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>OpenWorker 工作總控</title>
<style>
body{font-family:system-ui,-apple-system,"Segoe UI",sans-serif;margin:0;background:#111827;color:#e5e7eb}header{padding:14px 18px;background:#0b1220;position:sticky;top:0;z-index:3}h1{font-size:20px;margin:0 0 10px}.bar,.slotbar,.actions,.projectbar{display:flex;gap:8px;flex-wrap:wrap}input,select,button,.openlink{background:#1f2937;color:#e5e7eb;border:1px solid #374151;border-radius:7px;padding:7px}.openlink{text-decoration:none;display:inline-block;padding:5px 8px}button{cursor:pointer}main{padding:14px}.meta,.small{color:#9ca3af}.meta{margin:10px 0}.projectbar{margin:8px 0 12px}.projectcard{min-width:210px;max-width:310px;text-align:left}.projectcard.active{border-color:#60a5fa}.projectcard .name{font-weight:700;font-size:14px}.projectcard .counts{margin-top:4px}.grid{display:grid;grid-template-columns:minmax(0,1.45fr) minmax(380px,1fr);gap:12px}.panel{background:#172033;border:1px solid #27344a;border-radius:10px;overflow:hidden}.slotbar{margin-bottom:12px}.slot{min-width:175px;text-align:left}.slot.active{border-color:#60a5fa}.ok{color:#34d399}.bad{color:#fb7185}.warn{color:#fbbf24}table{width:100%;border-collapse:collapse;font-size:12px}th,td{padding:8px;border-bottom:1px solid #27344a;text-align:left;vertical-align:top}tr:hover{background:#1d2940}.status{font-weight:700}.succeeded{color:#34d399}.running,.starting{color:#fbbf24}.failed,.timed_out,.cancelled{color:#fb7185}.queued_local,.accepted{color:#60a5fa}.tabs{display:flex;gap:4px;padding:8px;border-bottom:1px solid #27344a}.tab.active{border-color:#60a5fa}.pane{padding:10px;max-height:74vh;overflow:auto}.group{border:1px solid #27344a;border-radius:8px;margin-bottom:8px;overflow:hidden}.group summary{padding:9px 10px;cursor:pointer;background:#131d2f;font-weight:700}.artifact{padding:10px;border-top:1px solid #27344a}.artifact:first-child{border-top:0}.badge{display:inline-block;padding:2px 6px;border:1px solid #374151;border-radius:999px;margin-right:4px;font-size:11px}.prov{color:#93c5fd;font-size:12px;margin:4px 0}.hash{font-family:monospace;font-size:11px;color:#9ca3af;word-break:break-all}.preview{margin-top:8px;max-width:100%;max-height:320px;border-radius:6px;background:#0b1220}.frame{width:100%;height:320px;border:0;background:white;border-radius:6px}.hidden{display:none}pre{white-space:pre-wrap;word-break:break-word;font-size:12px;margin:0}@media(max-width:950px){.grid{grid-template-columns:1fr}.slot,.projectcard{min-width:145px}}
</style></head><body>
<header><h1>OpenWorker 工作總控</h1><div class="bar"><input id="filter" placeholder="篩選 case / job / command"><select id="project"><option value="">全部項目</option></select><select id="status"><option value="">全部狀態</option><option>queued_local</option><option>starting</option><option>running</option><option>succeeded</option><option>failed</option><option>timed_out</option><option>cancelled</option></select><select id="kind"><option value="">全部成果類型</option></select><button onclick="clearProject()">全部項目</button><button onclick="clearSlot()">全部 Slot</button><button onclick="loadRecent()">近期全部成果</button><button onclick="loadAll()">重新整理</button><label class="small"><input type="checkbox" id="auto" checked> 3 秒更新</label></div></header>
<main><div class="meta" id="meta">載入中…</div><div id="projects" class="projectbar"></div><div id="slots" class="slotbar"></div><div class="grid"><div class="panel"><table><thead><tr><th>狀態</th><th>Job / Work</th><th>項目</th><th>Slot/PID</th><th>時間</th><th>成果</th></tr></thead><tbody id="jobs"></tbody></table></div><div class="panel"><div class="actions" style="padding:8px"><button onclick="jobAction('retry')">重試</button><button onclick="jobAction('cancel')">取消</button></div><div class="tabs"><button id="tSummary" class="tab active" onclick="tab('summary')">工作記錄</button><button id="tEvents" class="tab" onclick="tab('events')">Events</button><button id="tArtifacts" class="tab" onclick="tab('artifacts')">成果</button></div><div class="pane"><div id="summary">點選工作查看記錄。</div><pre id="events" class="hidden"></pre><div id="artifacts" class="hidden"></div></div></div></div></main>
<script>
let jobs=[],slots=[],selected='',slotFilter=0,detail=null,recent=[];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const tm=v=>{if(!v)return '';try{return new Date(v).toLocaleString()}catch{return v}};
const bytes=n=>{n=Number(n||0);if(n<1024)return n+' B';if(n<1048576)return(n/1024).toFixed(1)+' KB';if(n<1073741824)return(n/1048576).toFixed(1)+' MB';return(n/1073741824).toFixed(2)+' GB'};
const norm=v=>String(v||'').replace(/\\/g,'/').replace(/\/$/,'');
function projectOf(j){const p=norm(j.workspace_root||j.cwd);const a=p.split('/').filter(Boolean);return a[a.length-1]||'(未指定)'}
function activityOf(j){return j.finished_at||j.started_at||j.accepted_at||j.created_at||''}
function opts(){const p=document.getElementById('project'),old=p.value,vals=[...new Set(jobs.map(projectOf))].sort();p.innerHTML='<option value="">全部項目</option>'+vals.map(v=>'<option>'+esc(v)+'</option>').join('');if(vals.includes(old))p.value=old}
function projectStats(){const m=new Map();for(const j of jobs){const p=projectOf(j);if(!m.has(p))m.set(p,{name:p,total:0,ok:0,bad:0,running:0,last:'',lastJob:''});const x=m.get(p);x.total++;if(j.status==='succeeded')x.ok++;if(['failed','timed_out','cancelled'].includes(j.status))x.bad++;if(['running','starting','queued_local','accepted'].includes(j.status))x.running++;const a=activityOf(j);if(!x.last||new Date(a)>new Date(x.last)){x.last=a;x.lastJob=j.job_id}}return [...m.values()].sort((a,b)=>new Date(b.last)-new Date(a.last))}
function renderProjects(){const active=document.getElementById('project').value;document.getElementById('projects').innerHTML=projectStats().map(p=>'<button class="projectcard '+(active===p.name?'active':'')+'" onclick="selectProject(\''+esc(p.name)+'\')"><div class="name">'+esc(p.name)+'</div><div class="counts small"><span class="ok">成功 '+p.ok+'</span> ｜ <span class="bad">失敗 '+p.bad+'</span> ｜ <span class="warn">進行 '+p.running+'</span> ｜ 共 '+p.total+'</div><div class="small">最後：'+esc(tm(p.last))+'</div><div class="small">'+esc(p.lastJob||'')+'</div></button>').join('')}
function selectProject(name){document.getElementById('project').value=name;renderProjects();renderJobs();loadRecent()}
function clearProject(){document.getElementById('project').value='';renderProjects();renderJobs()}
async function loadAll(){try{const [a,b]=await Promise.all([fetch('/v1/jobs?limit=500',{cache:'no-store'}),fetch('/v1/slots?limit=500',{cache:'no-store'})]);jobs=(await a.json()).jobs||[];slots=(await b.json()).slots||[];opts();document.getElementById('meta').textContent='OpenWorker durable jobs: '+jobs.length+' ｜ 項目 '+projectStats().length+' ｜ '+new Date().toLocaleString();renderProjects();renderSlots();renderJobs();if(selected)loadDetail(selected)}catch(e){document.getElementById('meta').textContent='讀取失敗: '+e}}
function renderSlots(){document.getElementById('slots').innerHTML=slots.map(s=>'<button class="slot '+(slotFilter===s.slot?'active':'')+'" onclick="setSlot('+s.slot+')"><b>Slot '+s.slot+(s.current?' · '+esc(s.current.status):' · idle')+'</b><div class="small">'+(s.current?esc(s.current.job_id):'目前沒有工作')+'</div><div class="small"><span class="ok">成功 '+s.succeeded+'</span> ｜ <span class="bad">失敗 '+s.failed+'</span> ｜ 共 '+s.total+'</div></button>').join('')}
function setSlot(n){slotFilter=n;renderSlots();renderJobs()}function clearSlot(){slotFilter=0;renderSlots();renderJobs()}
function visible(){const q=document.getElementById('filter').value.toLowerCase(),st=document.getElementById('status').value,pr=document.getElementById('project').value;return jobs.filter(j=>(!slotFilter||j.agent_slot===slotFilter)&&(!st||j.status===st)&&(!pr||projectOf(j)===pr)&&(!q||JSON.stringify(j).toLowerCase().includes(q)))}
function renderJobs(){const rows=visible();document.getElementById('jobs').innerHTML=rows.map(j=>'<tr data-id="'+esc(j.job_id)+'"><td class="status '+esc(j.status)+'">'+esc(j.status)+'</td><td><b>'+esc(j.job_id)+'</b><div class="small">'+esc(j.command||'')+'</div></td><td>'+esc(projectOf(j))+'</td><td>slot '+esc(j.agent_slot||'-')+'<br>pid '+esc(j.pid||'-')+'</td><td>'+esc(tm(j.started_at||j.accepted_at||j.created_at))+'<br><span class="small">'+esc(tm(j.finished_at))+'</span></td><td><button onclick="event.stopPropagation();loadDetail(\''+esc(j.job_id)+'\',\'artifacts\')">查看成果</button></td></tr>').join('')||'<tr><td colspan="6">沒有符合條件的工作</td></tr>';document.querySelectorAll('tr[data-id]').forEach(x=>x.onclick=()=>loadDetail(x.dataset.id,'summary'))}
async function loadDetail(id,open){selected=id;const [a,b,c]=await Promise.all([fetch('/v1/jobs/'+encodeURIComponent(id),{cache:'no-store'}),fetch('/v1/jobs/'+encodeURIComponent(id)+'/events?limit=500',{cache:'no-store'}),fetch('/v1/jobs/'+encodeURIComponent(id)+'/artifacts?limit=500',{cache:'no-store'})]);const job=await a.json(),ev=await b.json(),ar=await c.json();detail={job,events:ev.events||[],artifacts:ar.artifacts||[]};refreshKinds(detail.artifacts);renderDetail();tab(open||'summary')}
function refreshKinds(a){const s=document.getElementById('kind'),old=s.value,vals=[...new Set(a.map(x=>x.kind).filter(Boolean))].sort();s.innerHTML='<option value="">全部成果類型</option>'+vals.map(v=>'<option>'+esc(v)+'</option>').join('');if(vals.includes(old))s.value=old}
function preview(x){if(!x.url)return '';if(x.kind==='image')return '<img class="preview" loading="lazy" src="'+esc(x.url)+'">';if(x.kind==='video')return '<video class="preview" controls preload="metadata" src="'+esc(x.url)+'"></video>';if(x.kind==='audio')return '<audio controls preload="metadata" src="'+esc(x.url)+'"></audio>';if(x.kind==='document'&&String(x.relative_path||x.path).toLowerCase().endsWith('.pdf'))return '<iframe class="frame" loading="lazy" src="'+esc(x.url)+'"></iframe>';return ''}
function card(x,j){return '<div class="artifact"><div class="prov">'+esc(projectOf(j))+' → '+esc(j.job_id)+' → Slot '+esc(j.agent_slot||'-')+' → PID '+esc(j.pid||'-')+' → 成果</div><b>'+esc(x.relative_path||x.path)+'</b><div><span class="badge">'+esc(x.role||'supporting')+'</span><span class="badge">'+esc(x.kind||'artifact')+'</span>'+(x.during_job_window?'<span class="badge">本工作產生</span>':'')+'</div><div class="small">'+bytes(x.size)+' ｜ '+esc(tm(x.modified_at))+'</div><div class="hash">SHA256 '+esc(x.sha256||'(大檔未計算)')+'</div><div class="small">'+esc(x.path)+'</div>'+(x.url?'<p><a class="openlink" target="_blank" rel="noopener" href="'+esc(x.url)+'">打開成果</a></p>':'')+preview(x)+'</div>'}
function grouped(items){const k=document.getElementById('kind').value;if(k)items=items.filter(x=>x.a.kind===k);const order=['deliverable','supporting','evidence','log'],names={deliverable:'交付成果',supporting:'輔助成果',evidence:'證據 / Receipt / Manifest',log:'執行日誌'};return order.map(role=>{const rows=items.filter(x=>(x.a.role||'supporting')===role);if(!rows.length)return '';const open=role==='deliverable'||role==='supporting'?' open':'';return '<details class="group"'+open+'><summary>'+names[role]+' ('+rows.length+')</summary>'+rows.map(x=>card(x.a,x.job)).join('')+'</details>'}).join('')||'<div class="small">沒有符合條件的成果。</div>'}
function renderDetail(){const j=detail.job;document.getElementById('summary').innerHTML='<b>'+esc(j.job_id)+'</b><p>項目：'+esc(projectOf(j))+'</p><p>狀態：<span class="status '+esc(j.status)+'">'+esc(j.status)+'</span></p><p>Slot '+esc(j.agent_slot||'-')+' / PID '+esc(j.pid||'-')+'</p><p>Workspace：'+esc(j.workspace_root||j.cwd||'')+'</p><pre>'+esc(JSON.stringify(j,null,2))+'</pre>';document.getElementById('events').textContent=JSON.stringify(detail.events,null,2);document.getElementById('artifacts').innerHTML=grouped(detail.artifacts.map(a=>({a,job:j})))}
async function loadRecent(){tab('artifacts');document.getElementById('artifacts').innerHTML='彙整中…';const js=visible().slice(0,40),all=(await Promise.all(js.map(async j=>{try{const r=await fetch('/v1/jobs/'+encodeURIComponent(j.job_id)+'/artifacts?limit=120',{cache:'no-store'}),x=await r.json();return(x.artifacts||[]).map(a=>({a,job:j}))}catch{return[]}}))).flat(),seen=new Set();recent=[];for(const x of all){const p=String(x.a.path||'').toLowerCase();if(!p||seen.has(p))continue;seen.add(p);recent.push(x)}recent.sort((a,b)=>(a.a.priority||999)-(b.a.priority||999)||new Date(b.a.modified_at)-new Date(a.a.modified_at));refreshKinds(recent.map(x=>x.a));document.getElementById('artifacts').innerHTML=grouped(recent)}
function tab(n){for(const x of ['summary','events','artifacts']){document.getElementById(x).classList.toggle('hidden',x!==n);document.getElementById('t'+x[0].toUpperCase()+x.slice(1)).classList.toggle('active',x===n)}}
async function jobAction(k){if(!selected){alert('請先選工作');return}if(k==='cancel'&&!confirm('確定取消 '+selected+'？'))return;const r=await fetch('/v1/jobs/'+encodeURIComponent(selected)+'/'+k,{method:'POST'});if(!r.ok){alert(await r.text());return}await loadAll();await loadDetail(selected,'summary')}
document.getElementById('filter').addEventListener('input',renderJobs);document.getElementById('project').addEventListener('change',()=>{renderProjects();renderJobs()});document.getElementById('status').addEventListener('change',renderJobs);document.getElementById('kind').addEventListener('change',()=>{if(recent.length)document.getElementById('artifacts').innerHTML=grouped(recent);else if(detail)renderDetail()});setInterval(()=>{if(document.getElementById('auto').checked)loadAll()},3000);loadAll();
</script></body></html>`
