package api

import(
 "encoding/json";"errors";"fmt";"net/http";"strconv";"strings";"time"
 "github.com/liuxb99/openworker/go-runtime/internal/buildinfo";"github.com/liuxb99/openworker/go-runtime/internal/cluster";"github.com/liuxb99/openworker/go-runtime/internal/inventory";"github.com/liuxb99/openworker/go-runtime/internal/model";owruntime "github.com/liuxb99/openworker/go-runtime/internal/runtime";"github.com/liuxb99/openworker/go-runtime/internal/store"
)
type Server struct{store *store.Store;runtime *owruntime.Manager;machine,advertise string;cluster *cluster.Controller;mux *http.ServeMux}
func New(st *store.Store,rt *owruntime.Manager,machine,advertise string,cc ...*cluster.Controller)*Server{var c *cluster.Controller;if len(cc)>0{c=cc[0]};s:=&Server{store:st,runtime:rt,machine:machine,advertise:strings.TrimRight(advertise,"/"),cluster:c,mux:http.NewServeMux()};s.routes();ensureNativeCaseContinueRoute(s);return s}
func(s *Server)Handler()http.Handler{return s.mux}
func writeJSON(w http.ResponseWriter,status int,v any){w.Header().Set("Content-Type","application/json");w.WriteHeader(status);_=json.NewEncoder(w).Encode(v)}
func writeErr(w http.ResponseWriter,status int,e error){writeJSON(w,status,map[string]any{"ok":false,"error":e.Error()})}
func(s *Server)routes(){s.mux.HandleFunc("GET /healthz",func(w http.ResponseWriter,r *http.Request){now:=time.Now().UTC();writeJSON(w,200,map[string]any{"ok":true,"machine":s.machine,"advertise_endpoint":s.advertise,"heartbeat_at":now,"lease_until":now.Add(15*time.Second),"build":buildinfo.Snapshot(),"service":buildinfo.ServiceSnapshot()})});s.mux.HandleFunc("GET /v1/node/info",func(w http.ResponseWriter,r *http.Request){writeJSON(w,200,map[string]any{"machine":s.machine,"advertise_endpoint":s.advertise,"build":buildinfo.Snapshot(),"service":buildinfo.ServiceSnapshot(),"inventory":inventory.Collect()})});s.mux.HandleFunc("GET /v1/node/status",func(w http.ResponseWriter,r *http.Request){now:=time.Now().UTC();v:=s.runtime.NodeStatus();v["node_id"]=strings.ToLower(s.machine);v["advertise_endpoint"]=s.advertise;v["heartbeat_at"]=now;v["lease_seconds"]=15;v["lease_until"]=now.Add(15*time.Second);v["build"]=buildinfo.Snapshot();v["service"]=buildinfo.ServiceSnapshot();v["inventory"]=inventory.Collect();writeJSON(w,200,v)});s.mux.HandleFunc("GET /v1/cluster/status",s.clusterStatus);s.mux.HandleFunc("GET /v1/cluster/capabilities",s.clusterCapabilities);s.mux.HandleFunc("GET /v1/cluster/route",s.clusterRoute);s.mux.HandleFunc("GET /v1/cluster/jobs",s.clusterJobs);s.mux.HandleFunc("GET /v1/cluster/jobs/{jobID}",s.clusterJobStatus);s.mux.HandleFunc("GET /v1/cluster/agents",s.clusterAgents);s.mux.HandleFunc("POST /v1/cluster/jobs",s.clusterSubmit);s.mux.HandleFunc("POST /v1/cluster/jobs/{jobID}/cancel",s.clusterCancel);s.mux.HandleFunc("POST /v1/cluster/jobs/{jobID}/retry",s.clusterRetry);s.mux.HandleFunc("POST /v1/cluster/queue/drain",s.clusterDrain);s.mux.HandleFunc("GET /v1/cluster/dispatches",s.clusterDispatches);s.mux.HandleFunc("GET /v1/cluster/dispatches/{jobID}",s.clusterDispatch);s.mux.HandleFunc("GET /v1/cluster/control-events",s.clusterControlEvents);s.mux.HandleFunc("GET /v1/cluster/endpoints",s.clusterEndpoints);s.mux.HandleFunc("GET /v1/cluster/connectivity",s.clusterConnectivity);s.mux.HandleFunc("POST /v1/jobs",s.submit);s.mux.HandleFunc("GET /v1/jobs",s.list);s.mux.HandleFunc("GET /v1/jobs/{jobID}",s.get);s.mux.HandleFunc("GET /v1/jobs/{jobID}/events",s.events);s.mux.HandleFunc("GET /v1/jobs/{jobID}/artifacts",s.artifacts);s.mux.HandleFunc("GET /v1/jobs/{jobID}/artifact",s.serveArtifact);s.mux.HandleFunc("GET /v1/slots",s.slots);s.mux.HandleFunc("POST /v1/jobs/{jobID}/cancel",s.cancel);s.mux.HandleFunc("POST /v1/jobs/{jobID}/retry",s.retry);s.mux.HandleFunc("POST /v1/queue/drain",s.drain);s.supervisorRoutes()}
func(s *Server)needCluster(w http.ResponseWriter)bool{if s.cluster==nil{writeErr(w,503,errors.New("cluster controller disabled"));return false};return true}
func(s *Server)clusterStatus(w http.ResponseWriter,r *http.Request){if !s.needCluster(w){return};v:=s.cluster.Status();v["jobs"]=s.cluster.JobCounts();writeJSON(w,200,v)}
func(s *Server)clusterCapabilities(w http.ResponseWriter,r *http.Request){if !s.needCluster(w){return};writeJSON(w,200,s.cluster.Capabilities())}
func(s *Server)clusterRoute(w http.ResponseWriter,r *http.Request){if !s.needCluster(w){return};caps:=csv(r.URL.Query().Get("capabilities"));n,e:=s.cluster.Registry().Select(r.URL.Query().Get("machine"),caps);if e!=nil{writeErr(w,409,e);return};writeJSON(w,200,map[string]any{"selected":n,"required_capabilities":caps})}
func(s *Server)clusterJobs(w http.ResponseWriter,r *http.Request){if !s.needCluster(w){return};limit:=queryInt(r,"limit",100);jobs,e:=s.cluster.Jobs(limit);if e!=nil&&len(jobs)==0{writeErr(w,502,e);return};writeJSON(w,200,map[string]any{"jobs":jobs,"count":len(jobs),"partial_error":errText(e)})}
func(s *Server)clusterJobStatus(w http.ResponseWriter,r *http.Request){if !s.needCluster(w){return};j,e:=s.cluster.JobStatus(r.PathValue("jobID"));if e!=nil{writeErr(w,404,e);return};writeJSON(w,200,j)}
func(s *Server)clusterAgents(w http.ResponseWriter,r *http.Request){if !s.needCluster(w){return};a,e:=s.cluster.Agents();if e!=nil&&len(a)==0{writeErr(w,502,e);return};writeJSON(w,200,map[string]any{"agents":a,"count":len(a),"partial_error":errText(e)})}
func(s *Server)clusterSubmit(w http.ResponseWriter,r *http.Request){if !s.needCluster(w){return};var req cluster.SubmitRequest;d:=json.NewDecoder(http.MaxBytesReader(w,r.Body,1<<20));d.DisallowUnknownFields();if e:=d.Decode(&req);e!=nil{writeErr(w,400,e);return};requested:=req.Job.Machine;res,e:=s.cluster.Submit(req);if e!=nil{_=s.store.RecordClusterControl(req.Job.JobID,"submit_failed",requested,e.Error());writeErr(w,409,e);return};_=s.store.RecordClusterDispatch(store.ClusterDispatch{JobID:req.Job.JobID,DispatchID:req.Job.DispatchID,RequestedMachine:requested,SelectedNodeID:res.Selected.NodeID,SelectedMachine:res.Selected.Machine,Endpoint:res.Selected.Endpoint,RequiredCapabilities:req.RequiredCapabilities,AcceptedAt:res.Ack.AcceptedAt});_=s.store.RecordClusterControl(req.Job.JobID,"submit",res.Selected.NodeID,"durable ACK accepted");writeJSON(w,202,res)}
func(s *Server)clusterCancel(w http.ResponseWriter,r *http.Request){s.clusterAction(w,r,"cancel")}
func(s *Server)clusterRetry(w http.ResponseWriter,r *http.Request){s.clusterAction(w,r,"retry")}
func(s *Server)clusterAction(w http.ResponseWriter,r *http.Request,action string){if !s.needCluster(w){return};id:=r.PathValue("jobID");res,e:=s.cluster.JobAction(id,action);if e!=nil{_=s.store.RecordClusterControl(id,action+"_failed","",e.Error());writeErr(w,409,e);return};_=s.store.RecordClusterControl(id,action,res.NodeID,"forwarded to "+res.Endpoint);writeJSON(w,200,res)}
func(s *Server)clusterDrain(w http.ResponseWriter,r *http.Request){if !s.needCluster(w){return};machine:=r.URL.Query().Get("machine");mode:=strings.ToLower(r.URL.Query().Get("mode"));if mode==""{mode="queued"};res,e:=s.cluster.Drain(machine,mode);if e!=nil{_=s.store.RecordClusterControl("","drain_failed",machine,e.Error());writeErr(w,409,e);return};_=s.store.RecordClusterControl("","drain."+mode,machine,fmt.Sprintf("forwarded to %d node(s)",len(res)));writeJSON(w,200,map[string]any{"ok":true,"machine":machine,"mode":mode,"results":res,"count":len(res)})}
func(s *Server)clusterDispatches(w http.ResponseWriter,r *http.Request){rows,e:=s.store.ClusterDispatches(queryInt(r,"limit",100));if e!=nil{writeErr(w,500,e);return};writeJSON(w,200,map[string]any{"dispatches":rows,"count":len(rows)})}
func(s *Server)clusterDispatch(w http.ResponseWriter,r *http.Request){v,e:=s.store.ClusterDispatch(r.PathValue("jobID"));if e!=nil{writeErr(w,404,e);return};writeJSON(w,200,v)}
func(s *Server)clusterControlEvents(w http.ResponseWriter,r *http.Request){rows,e:=s.store.ClusterControlEvents(r.URL.Query().Get("job_id"),queryInt(r,"limit",100));if e!=nil{writeErr(w,500,e);return};writeJSON(w,200,map[string]any{"events":rows,"count":len(rows)})}
func(s *Server)clusterEndpoints(w http.ResponseWriter,r *http.Request){rows,e:=s.store.ClusterEndpoints();if e!=nil{writeErr(w,500,e);return};writeJSON(w,200,map[string]any{"endpoints":rows,"count":len(rows)})}
func(s *Server)clusterConnectivity(w http.ResponseWriter,r *http.Request){rows,e:=s.store.ClusterConnectivityHistory(queryInt(r,"limit",200));if e!=nil{writeErr(w,500,e);return};writeJSON(w,200,map[string]any{"observations":rows,"count":len(rows)})}
func errText(e error)string{if e==nil{return ""};return e.Error()};func csv(v string)[]string{out:=[]string{};for _,x:=range strings.Split(v,","){if x=strings.TrimSpace(x);x!=""{out=append(out,x)}};return out};func queryInt(r *http.Request,k string,d int)int{if v:=r.URL.Query().Get(k);v!=""{if n,e:=strconv.Atoi(v);e==nil{return n}};return d}
func(s *Server)submit(w http.ResponseWriter,r *http.Request){var req model.SubmitRequest;d:=json.NewDecoder(http.MaxBytesReader(w,r.Body,1<<20));d.DisallowUnknownFields();if e:=d.Decode(&req);e!=nil{writeErr(w,400,e);return};if e:=owruntime.ValidateCWD(req.CWD);e!=nil{writeErr(w,400,e);return};ack,e:=s.store.Submit(req,s.machine);if e!=nil{writeErr(w,409,e);return};writeJSON(w,202,ack)}
func(s *Server)list(w http.ResponseWriter,r *http.Request){jobs,e:=s.store.List(queryInt(r,"limit",100));if e!=nil{writeErr(w,500,e);return};writeJSON(w,200,map[string]any{"jobs":jobs})}
func(s *Server)get(w http.ResponseWriter,r *http.Request){j,e:=s.store.Get(r.PathValue("jobID"));if e!=nil{writeErr(w,404,e);return};writeJSON(w,200,j)}
func(s *Server)events(w http.ResponseWriter,r *http.Request){events,e:=s.store.Events(r.PathValue("jobID"),queryInt(r,"limit",100));if e!=nil{writeErr(w,500,e);return};writeJSON(w,200,map[string]any{"job_id":r.PathValue("jobID"),"events":events})}
func(s *Server)cancel(w http.ResponseWriter,r *http.Request){id:=r.PathValue("jobID");if e:=s.runtime.Cancel(id);e!=nil{writeErr(w,404,e);return};j,_:=s.store.Get(id);writeJSON(w,200,j)}
func(s *Server)retry(w http.ResponseWriter,r *http.Request){id:=r.PathValue("jobID");if e:=s.runtime.Retry(id);e!=nil{writeErr(w,409,e);return};j,_:=s.store.Get(id);writeJSON(w,202,j)}
func(s *Server)drain(w http.ResponseWriter,r *http.Request){mode:=strings.ToLower(r.URL.Query().Get("mode"));if mode==""{mode="queued"};var ids []string;var e error;switch mode{case"queued":ids,e=s.runtime.DrainQueued();case"all":ids,e=s.runtime.DrainAll();default:e=errors.New("mode must be queued or all")};if e!=nil{writeErr(w,500,e);return};writeJSON(w,200,map[string]any{"ok":true,"mode":mode,"drained_job_ids":ids,"count":len(ids)})}